package cn.nukkit.item;

import cn.nukkit.math.Mth;

import static cn.nukkit.item.Items.BASE_INTERNAL_ID;

/**
 * Nukkit runtime item IDs.
 */
public interface ItemRuntimeID {
    int COPPER_INGOT = BASE_INTERNAL_ID + 1;
    int GLOW_BERRIES = BASE_INTERNAL_ID + 2;
    int CHEST_BOAT = BASE_INTERNAL_ID + 3;
    int BAMBOO_SIGN = BASE_INTERNAL_ID + 4;
    int TORCHFLOWER_SEEDS = BASE_INTERNAL_ID + 5;
    int ARCHER_POTTERY_SHERD = BASE_INTERNAL_ID + 6;
    int ARMS_UP_POTTERY_SHERD = BASE_INTERNAL_ID + 7;
    int PRIZE_POTTERY_SHERD = BASE_INTERNAL_ID + 8;
    int SKULL_POTTERY_SHERD = BASE_INTERNAL_ID + 9;
    int BRUSH = BASE_INTERNAL_ID + 10;
    int CHERRY_SIGN = BASE_INTERNAL_ID + 11;
    int NETHERITE_UPGRADE_SMITHING_TEMPLATE = BASE_INTERNAL_ID + 12;
    int SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE = BASE_INTERNAL_ID + 13;
    int DUNE_ARMOR_TRIM_SMITHING_TEMPLATE = BASE_INTERNAL_ID + 14;
    int COAST_ARMOR_TRIM_SMITHING_TEMPLATE = BASE_INTERNAL_ID + 15;
    int WILD_ARMOR_TRIM_SMITHING_TEMPLATE = BASE_INTERNAL_ID + 16;
    int WARD_ARMOR_TRIM_SMITHING_TEMPLATE = BASE_INTERNAL_ID + 17;
    int EYE_ARMOR_TRIM_SMITHING_TEMPLATE = BASE_INTERNAL_ID + 18;
    int VEX_ARMOR_TRIM_SMITHING_TEMPLATE = BASE_INTERNAL_ID + 19;
    int TIDE_ARMOR_TRIM_SMITHING_TEMPLATE = BASE_INTERNAL_ID + 20;
    int SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE = BASE_INTERNAL_ID + 21;
    int RIB_ARMOR_TRIM_SMITHING_TEMPLATE = BASE_INTERNAL_ID + 22;
    int SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE = BASE_INTERNAL_ID + 23;
    int ANGLER_POTTERY_SHERD = BASE_INTERNAL_ID + 24;
    int BLADE_POTTERY_SHERD = BASE_INTERNAL_ID + 25;
    int BREWER_POTTERY_SHERD = BASE_INTERNAL_ID + 26;
    int BURN_POTTERY_SHERD = BASE_INTERNAL_ID + 27;
    int DANGER_POTTERY_SHERD = BASE_INTERNAL_ID + 28;
    int EXPLORER_POTTERY_SHERD = BASE_INTERNAL_ID + 29;
    int FRIEND_POTTERY_SHERD = BASE_INTERNAL_ID + 30;
    int HEART_POTTERY_SHERD = BASE_INTERNAL_ID + 31;
    int HEARTBREAK_POTTERY_SHERD = BASE_INTERNAL_ID + 32;
    int HOWL_POTTERY_SHERD = BASE_INTERNAL_ID + 33;
    int MINER_POTTERY_SHERD = BASE_INTERNAL_ID + 34;
    int MOURNER_POTTERY_SHERD = BASE_INTERNAL_ID + 35;
    int PLENTY_POTTERY_SHERD = BASE_INTERNAL_ID + 36;
    int SHEAF_POTTERY_SHERD = BASE_INTERNAL_ID + 37;
    int SHELTER_POTTERY_SHERD = BASE_INTERNAL_ID + 38;
    int SNORT_POTTERY_SHERD = BASE_INTERNAL_ID + 39;
    int SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE = BASE_INTERNAL_ID + 40;
    int WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE = BASE_INTERNAL_ID + 41;
    int RAISER_ARMOR_TRIM_SMITHING_TEMPLATE = BASE_INTERNAL_ID + 42;
    int SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE = BASE_INTERNAL_ID + 43;
    int HOST_ARMOR_TRIM_SMITHING_TEMPLATE = BASE_INTERNAL_ID + 44;
    int PITCHER_POD = BASE_INTERNAL_ID + 45;
    int ARMADILLO_SCUTE = BASE_INTERNAL_ID + 46;
    int WOLF_ARMOR = BASE_INTERNAL_ID + 47;
    int TRIAL_KEY = BASE_INTERNAL_ID + 48;
    int OMINOUS_TRIAL_KEY = BASE_INTERNAL_ID + 49;
    int OMINOUS_BOTTLE = BASE_INTERNAL_ID + 50;
    int BREEZE_ROD = BASE_INTERNAL_ID + 51;
    int WIND_CHARGE = BASE_INTERNAL_ID + 52;
    int MACE = BASE_INTERNAL_ID + 53;
    int FLOW_POTTERY_SHERD = BASE_INTERNAL_ID + 54;
    int GUSTER_POTTERY_SHERD = BASE_INTERNAL_ID + 55;
    int SCRAPE_POTTERY_SHERD = BASE_INTERNAL_ID + 56;
    int FLOW_ARMOR_TRIM_SMITHING_TEMPLATE = BASE_INTERNAL_ID + 57;
    int BOLT_ARMOR_TRIM_SMITHING_TEMPLATE = BASE_INTERNAL_ID + 58;
    int BUNDLE = BASE_INTERNAL_ID + 59;
    int BLACK_BUNDLE = BASE_INTERNAL_ID + 60;
    int BLUE_BUNDLE = BASE_INTERNAL_ID + 61;
    int BROWN_BUNDLE = BASE_INTERNAL_ID + 62;
    int CYAN_BUNDLE = BASE_INTERNAL_ID + 63;
    int GRAY_BUNDLE = BASE_INTERNAL_ID + 64;
    int GREEN_BUNDLE = BASE_INTERNAL_ID + 65;
    int LIGHT_BLUE_BUNDLE = BASE_INTERNAL_ID + 66;
    int LIGHT_GRAY_BUNDLE = BASE_INTERNAL_ID + 67;
    int LIME_BUNDLE = BASE_INTERNAL_ID + 68;
    int MAGENTA_BUNDLE = BASE_INTERNAL_ID + 69;
    int ORANGE_BUNDLE = BASE_INTERNAL_ID + 70;
    int PINK_BUNDLE = BASE_INTERNAL_ID + 71;
    int PURPLE_BUNDLE = BASE_INTERNAL_ID + 72;
    int RED_BUNDLE = BASE_INTERNAL_ID + 73;
    int WHITE_BUNDLE = BASE_INTERNAL_ID + 74;
    int YELLOW_BUNDLE = BASE_INTERNAL_ID + 75;
    int PALE_OAK_SIGN = BASE_INTERNAL_ID + 76;
    int RESIN_BRICK = BASE_INTERNAL_ID + 77;
    int BLUE_EGG = BASE_INTERNAL_ID + 78;
    int BROWN_EGG = BASE_INTERNAL_ID + 79;

    int CUSTOM_ITEM = Mth.smallestEncompassingPowerOfTwo(BASE_INTERNAL_ID + 80); //2048
}
