package cn.nukkit.item;

public interface ItemBlockNames {
    String STONE = "stone";
    String GRASS_BLOCK = "grass_block";
    String GRASS = "grass";
    String DIRT = "dirt";
    String COBBLESTONE = "cobblestone";
    String OAK_PLANKS = "oak_planks"; //TODO: 1.20.50 flattening
    String PLANKS = "planks";
    String OAK_SAPLING = "oak_sapling"; //TODO: 1.20.80 flattening
    String SAPLING = "sapling";
    String BEDROCK = "bedrock";
    String FLOWING_WATER = "flowing_water";
    String WATER = "water";
    String FLOWING_LAVA = "flowing_lava";
    String LAVA = "lava";
    String SAND = "sand";
    String GRAVEL = "gravel";
    String GOLD_ORE = "gold_ore";
    String IRON_ORE = "iron_ore";
    String COAL_ORE = "coal_ore";
    String OAK_LOG = "oak_log"; //TODO: 1.19.80 flattening
    String LOG = "log";
    String OAK_LEAVES = "oak_leaves";
    String LEAVES = "leaves";
    String SPONGE = "sponge";
    String GLASS = "glass";
    String LAPIS_ORE = "lapis_ore";
    String LAPIS_BLOCK = "lapis_block";
    String DISPENSER = "dispenser";
    String SANDSTONE = "sandstone";
    String NOTEBLOCK = "noteblock";
    String ITEM_BED = "item.bed";
    String GOLDEN_RAIL = "golden_rail";
    String DETECTOR_RAIL = "detector_rail";
    String STICKY_PISTON = "sticky_piston";
    String WEB = "web";
    String SHORT_GRASS = "short_grass";
    String TALLGRASS = "tallgrass";
    String DEADBUSH = "deadbush";
    String PISTON = "piston";
    String PISTON_ARM_COLLISION = "pistonarmcollision"; //TODO: 1.18.30 rename
    String PISTON_ARM_COLLISION_NEW = "piston_arm_collision";
    String WHITE_WOOL = "white_wool"; //TODO: 1.19.70 flattening
    String WOOL = "wool";
    String ELEMENT_0 = "element_0";
    String DANDELION = "dandelion";
    String YELLOW_FLOWER = "yellow_flower";
    String POPPY = "poppy"; //TODO: 1.20.80 flattening
    String RED_FLOWER = "red_flower";
    String BROWN_MUSHROOM = "brown_mushroom";
    String RED_MUSHROOM = "red_mushroom";
    String GOLD_BLOCK = "gold_block";
    String IRON_BLOCK = "iron_block";
    String SMOOTH_STONE_DOUBLE_SLAB = "smooth_stone_double_slab"; //TODO: 1.21.20 flattening
    String REAL_DOUBLE_STONE_SLAB = "real_double_stone_slab"; //TODO: 1.19.0 rename
    String DOUBLE_STONE_BLOCK_SLAB = "double_stone_block_slab";
    String SMOOTH_STONE_SLAB = "smooth_stone_slab"; //TODO: 1.21.0 flattening
    String DOUBLE_STONE_SLAB = "double_stone_slab"; //TODO: 1.19.0 rename
    String STONE_BLOCK_SLAB = "stone_block_slab";
    String BRICK_BLOCK = "brick_block";
    String TNT = "tnt";
    String BOOKSHELF = "bookshelf";
    String MOSSY_COBBLESTONE = "mossy_cobblestone";
    String OBSIDIAN = "obsidian";
    String TORCH = "torch";
    String FIRE = "fire";
    String MOB_SPAWNER = "mob_spawner";
    String OAK_STAIRS = "oak_stairs";
    String CHEST = "chest";
    String REDSTONE_WIRE = "redstone_wire";
    String DIAMOND_ORE = "diamond_ore";
    String DIAMOND_BLOCK = "diamond_block";
    String CRAFTING_TABLE = "crafting_table";
    String ITEM_WHEAT = "item.wheat";
    String FARMLAND = "farmland";
    String FURNACE = "furnace";
    String LIT_FURNACE = "lit_furnace";
    String STANDING_SIGN = "standing_sign";
    String ITEM_WOODEN_DOOR = "item.wooden_door";
    String LADDER = "ladder";
    String RAIL = "rail";
    String STONE_STAIRS = "stone_stairs";
    String WALL_SIGN = "wall_sign";
    String LEVER = "lever";
    String STONE_PRESSURE_PLATE = "stone_pressure_plate";
    String ITEM_IRON_DOOR = "item.iron_door";
    String WOODEN_PRESSURE_PLATE = "wooden_pressure_plate";
    String REDSTONE_ORE = "redstone_ore";
    String LIT_REDSTONE_ORE = "lit_redstone_ore";
    String UNLIT_REDSTONE_TORCH = "unlit_redstone_torch";
    String REDSTONE_TORCH = "redstone_torch";
    String STONE_BUTTON = "stone_button";
    String SNOW_LAYER = "snow_layer";
    String ICE = "ice";
    String SNOW = "snow";
    String CACTUS = "cactus";
    String CLAY = "clay";
    String ITEM_REEDS = "item.reeds";
    String JUKEBOX = "jukebox";
    String OAK_FENCE = "oak_fence"; //TODO: 1.19.80 flattening
    String FENCE = "fence";
    String PUMPKIN = "pumpkin";
    String NETHERRACK = "netherrack";
    String SOUL_SAND = "soul_sand";
    String GLOWSTONE = "glowstone";
    String PORTAL = "portal";
    String LIT_PUMPKIN = "lit_pumpkin";
    String ITEM_CAKE = "item.cake";
    String UNPOWERED_REPEATER = "unpowered_repeater";
    String POWERED_REPEATER = "powered_repeater";
    String INVISIBLE_BEDROCK = "invisiblebedrock"; //TODO: 1.18.30 rename
    String INVISIBLE_BEDROCK_NEW = "invisible_bedrock";
    String TRAPDOOR = "trapdoor";
    String INFESTED_STONE = "infested_stone"; //TODO: 1.21.20 flattening
    String MONSTER_EGG = "monster_egg";
    String STONE_BRICKS = "stone_bricks"; //TODO: 1.21.20 flattening
    String STONEBRICK = "stonebrick";
    String BROWN_MUSHROOM_BLOCK = "brown_mushroom_block";
    String RED_MUSHROOM_BLOCK = "red_mushroom_block";
    String IRON_BARS = "iron_bars";
    String GLASS_PANE = "glass_pane";
    String MELON_BLOCK = "melon_block";
    String PUMPKIN_STEM = "pumpkin_stem";
    String MELON_STEM = "melon_stem";
    String VINE = "vine";
    String FENCE_GATE = "fence_gate";
    String BRICK_STAIRS = "brick_stairs";
    String STONE_BRICK_STAIRS = "stone_brick_stairs";
    String MYCELIUM = "mycelium";
    String WATERLILY = "waterlily";
    String NETHER_BRICK = "nether_brick";
    String NETHER_BRICK_FENCE = "nether_brick_fence";
    String NETHER_BRICK_STAIRS = "nether_brick_stairs";
    String ITEM_NETHER_WART = "item.nether_wart";
    String ENCHANTING_TABLE = "enchanting_table";
    String ITEM_BREWING_STAND = "brewingstandblock"; //TODO: 1.18.30: rename
    String ITEM_BREWING_STAND_NEW = "item.brewing_stand";
    String ITEM_CAULDRON = "item.cauldron";
    String END_PORTAL = "end_portal";
    String END_PORTAL_FRAME = "end_portal_frame";
    String END_STONE = "end_stone";
    String DRAGON_EGG = "dragon_egg";
    String REDSTONE_LAMP = "redstone_lamp";
    String LIT_REDSTONE_LAMP = "lit_redstone_lamp";
    String DROPPER = "dropper";
    String ACTIVATOR_RAIL = "activator_rail";
    String COCOA = "cocoa";
    String SANDSTONE_STAIRS = "sandstone_stairs";
    String EMERALD_ORE = "emerald_ore";
    String ENDER_CHEST = "ender_chest";
    String TRIPWIRE_HOOK = "tripwire_hook";
    String TRIP_WIRE = "tripwire"; //TODO: 1.18.30 rename
    String TRIP_WIRE_NEW = "trip_wire";
    String EMERALD_BLOCK = "emerald_block";
    String SPRUCE_STAIRS = "spruce_stairs";
    String BIRCH_STAIRS = "birch_stairs";
    String JUNGLE_STAIRS = "jungle_stairs";
    String COMMAND_BLOCK = "command_block";
    String BEACON = "beacon";
    String COBBLESTONE_WALL = "cobblestone_wall";
    String ITEM_FLOWER_POT = "item.flower_pot";
    String CARROTS = "carrots";
    String POTATOES = "potatoes";
    String WOODEN_BUTTON = "wooden_button";
    String ITEM_SKULL = "item.skull";
    String ANVIL = "anvil";
    String TRAPPED_CHEST = "trapped_chest";
    String LIGHT_WEIGHTED_PRESSURE_PLATE = "light_weighted_pressure_plate";
    String HEAVY_WEIGHTED_PRESSURE_PLATE = "heavy_weighted_pressure_plate";
    String UNPOWERED_COMPARATOR = "unpowered_comparator";
    String POWERED_COMPARATOR = "powered_comparator";
    String DAYLIGHT_DETECTOR = "daylight_detector";
    String REDSTONE_BLOCK = "redstone_block";
    String QUARTZ_ORE = "quartz_ore";
    String ITEM_HOPPER = "item.hopper";
    String QUARTZ_BLOCK = "quartz_block";
    String QUARTZ_STAIRS = "quartz_stairs";
    String OAK_DOUBLE_SLAB = "oak_double_slab"; //TODO: 1.20.70 flattening
    String DOUBLE_WOODEN_SLAB = "double_wooden_slab";
    String OAK_SLAB = "oak_slab"; //TODO: 1.20.70 flattening
    String WOODEN_SLAB = "wooden_slab";
    String WHITE_TERRACOTTA = "white_terracotta"; //TODO: 1.20.30 flattening
    String STAINED_HARDENED_CLAY = "stained_hardened_clay";
    String WHITE_STAINED_GLASS_PANE = "white_stained_glass_pane"; //TODO: 1.20.20 flattening
    String STAINED_GLASS_PANE = "stained_glass_pane";
    String ACACIA_LEAVES = "acacia_leaves"; //TODO: 1.20.70 flattening
    String LEAVES2 = "leaves2";
    String ACACIA_LOG = "acacia_log"; //TODO: 1.19.80 flattening
    String LOG2 = "log2";
    String ACACIA_STAIRS = "acacia_stairs";
    String DARK_OAK_STAIRS = "dark_oak_stairs";
    String SLIME = "slime";

    String IRON_TRAPDOOR = "iron_trapdoor";
    String PRISMARINE = "prismarine";
    String SEA_LANTERN = "sealantern"; //TODO: 1.18.30 rename
    String SEA_LANTERN_NEW = "sea_lantern";
    String HAY_BLOCK = "hay_block";
    String WHITE_CARPET = "white_carpet"; //TODO: 1.20.0 flattening
    String CARPET = "carpet";
    String HARDENED_CLAY = "hardened_clay";
    String COAL_BLOCK = "coal_block";
    String PACKED_ICE = "packed_ice";
    String SUNFLOWER = "sunflower"; //TODO: 1.21.0 flattening
    String DOUBLE_PLANT = "double_plant";
    String STANDING_BANNER = "standing_banner";
    String WALL_BANNER = "wall_banner";
    String DAYLIGHT_DETECTOR_INVERTED = "daylight_detector_inverted";
    String RED_SANDSTONE = "red_sandstone";
    String RED_SANDSTONE_STAIRS = "red_sandstone_stairs";
    String RED_SANDSTONE_DOUBLE_SLAB = "red_sandstone_double_slab"; //TODO: 1.21.20 flattening
    String REAL_DOUBLE_STONE_SLAB2 = "real_double_stone_slab2"; //TODO: 1.19.0 rename
    String DOUBLE_STONE_BLOCK_SLAB2 = "double_stone_block_slab2";
    String RED_SANDSTONE_SLAB = "red_sandstone_slab"; //TODO: 1.21.20 flattening
    String DOUBLE_STONE_SLAB2 = "double_stone_slab2"; //TODO: 1.19.0 rename
    String STONE_BLOCK_SLAB2 = "stone_block_slab2";
    String SPRUCE_FENCE_GATE = "spruce_fence_gate";
    String BIRCH_FENCE_GATE = "birch_fence_gate";
    String JUNGLE_FENCE_GATE = "jungle_fence_gate";
    String DARK_OAK_FENCE_GATE = "dark_oak_fence_gate";
    String ACACIA_FENCE_GATE = "acacia_fence_gate";
    String REPEATING_COMMAND_BLOCK = "repeating_command_block";
    String CHAIN_COMMAND_BLOCK = "chain_command_block";
    String HARD_GLASS_PANE = "hard_glass_pane";
    String HARD_WHITE_STAINED_GLASS_PANE = "hard_white_stained_glass_pane"; //TODO: 1.20.60 flattening
    String HARD_STAINED_GLASS_PANE = "hard_stained_glass_pane";
    String CHEMICAL_HEAT = "chemical_heat";
    String ITEM_SPRUCE_DOOR = "item.spruce_door";
    String ITEM_BIRCH_DOOR = "item.birch_door";
    String ITEM_JUNGLE_DOOR = "item.jungle_door";
    String ITEM_ACACIA_DOOR = "item.acacia_door";
    String ITEM_DARK_OAK_DOOR = "item.dark_oak_door";
    String GRASS_PATH = "grass_path";
    String ITEM_FRAME = "item.frame";
    String CHORUS_FLOWER = "chorus_flower";
    String PURPUR_BLOCK = "purpur_block";
    String COLORED_TORCH_RED = "colored_torch_red"; //TODO: 1.21.30 flattening
    String COLORED_TORCH_RG = "colored_torch_rg";
    String PURPUR_STAIRS = "purpur_stairs";
    String COLORED_TORCH_BLUE = "colored_torch_blue"; //TODO: 1.21.30 flattening
    String COLORED_TORCH_BP = "colored_torch_bp";
    String UNDYED_SHULKER_BOX = "undyed_shulker_box";
    String END_BRICKS = "end_bricks";
    String FROSTED_ICE = "frosted_ice";
    String END_ROD = "end_rod";
    String END_GATEWAY = "end_gateway";
    String ALLOW = "allow";
    String DENY = "deny";
    String BORDER_BLOCK = "border_block";
    String MAGMA = "magma";
    String NETHER_WART_BLOCK = "nether_wart_block";
    String RED_NETHER_BRICK = "red_nether_brick";
    String BONE_BLOCK = "bone_block";
    String STRUCTURE_VOID = "structure_void";
    String WHITE_SHULKER_BOX = "white_shulker_box"; //TODO: 1.20.10 flattening
    String SHULKER_BOX = "shulker_box";
    /**
     * @deprecated (1.12.0) use {@link #PURPLE_GLAZED_TERRACOTTA} instead
     */
    @Deprecated
    String GLAZED_TERRACOTTA_PURPLE = "glazedterracotta.purple";
    String PURPLE_GLAZED_TERRACOTTA = "purple_glazed_terracotta";
    /**
     * @deprecated (1.12.0) use {@link #WHITE_GLAZED_TERRACOTTA} instead
     */
    @Deprecated
    String GLAZED_TERRACOTTA_WHITE = "glazedterracotta.white";
    String WHITE_GLAZED_TERRACOTTA = "white_glazed_terracotta";
    /**
     * @deprecated (1.12.0) use {@link #ORANGE_GLAZED_TERRACOTTA} instead
     */
    @Deprecated
    String GLAZED_TERRACOTTA_ORANGE = "glazedterracotta.orange";
    String ORANGE_GLAZED_TERRACOTTA = "orange_glazed_terracotta";
    /**
     * @deprecated (1.12.0) use {@link #MAGENTA_GLAZED_TERRACOTTA} instead
     */
    @Deprecated
    String GLAZED_TERRACOTTA_MAGENTA = "glazedterracotta.magenta";
    String MAGENTA_GLAZED_TERRACOTTA = "magenta_glazed_terracotta";
    /**
     * @deprecated (1.12.0) use {@link #LIGHT_BLUE_GLAZED_TERRACOTTA} instead
     */
    @Deprecated
    String GLAZED_TERRACOTTA_LIGHT_BLUE = "glazedterracotta.light_blue";
    String LIGHT_BLUE_GLAZED_TERRACOTTA = "light_blue_glazed_terracotta";
    /**
     * @deprecated (1.12.0) use {@link #YELLOW_GLAZED_TERRACOTTA} instead
     */
    @Deprecated
    String GLAZED_TERRACOTTA_YELLOW = "glazedterracotta.yellow";
    String YELLOW_GLAZED_TERRACOTTA = "yellow_glazed_terracotta";
    /**
     * @deprecated (1.12.0) use {@link #LIME_GLAZED_TERRACOTTA} instead
     */
    @Deprecated
    String GLAZED_TERRACOTTA_LIME = "glazedterracotta.lime";
    String LIME_GLAZED_TERRACOTTA = "lime_glazed_terracotta";
    /**
     * @deprecated (1.12.0) use {@link #PINK_GLAZED_TERRACOTTA} instead
     */
    @Deprecated
    String GLAZED_TERRACOTTA_PINK = "glazedterracotta.pink";
    String PINK_GLAZED_TERRACOTTA = "pink_glazed_terracotta";
    /**
     * @deprecated (1.12.0) use {@link #GRAY_GLAZED_TERRACOTTA} instead
     */
    @Deprecated
    String GLAZED_TERRACOTTA_GRAY = "glazedterracotta.gray";
    String GRAY_GLAZED_TERRACOTTA = "gray_glazed_terracotta";
    /**
     * @deprecated (1.12.0) use {@link #SILVER_GLAZED_TERRACOTTA} instead
     */
    @Deprecated
    String GLAZED_TERRACOTTA_SILVER = "glazedterracotta.silver";
    String SILVER_GLAZED_TERRACOTTA = "silver_glazed_terracotta";
    /**
     * @deprecated (1.12.0) use {@link #CYAN_GLAZED_TERRACOTTA} instead
     */
    @Deprecated
    String GLAZED_TERRACOTTA_CYAN = "glazedterracotta.cyan";
    String CYAN_GLAZED_TERRACOTTA = "cyan_glazed_terracotta";
    String CHALKBOARD = "chalkboard";
    /**
     * @deprecated (1.12.0) use {@link #BLUE_GLAZED_TERRACOTTA} instead
     */
    @Deprecated
    String GLAZED_TERRACOTTA_BLUE = "glazedterracotta.blue";
    String BLUE_GLAZED_TERRACOTTA = "blue_glazed_terracotta";
    /**
     * @deprecated (1.12.0) use {@link #BROWN_GLAZED_TERRACOTTA} instead
     */
    @Deprecated
    String GLAZED_TERRACOTTA_BROWN = "glazedterracotta.brown";
    String BROWN_GLAZED_TERRACOTTA = "brown_glazed_terracotta";
    /**
     * @deprecated (1.12.0) use {@link #GREEN_GLAZED_TERRACOTTA} instead
     */
    @Deprecated
    String GLAZED_TERRACOTTA_GREEN = "glazedterracotta.green";
    String GREEN_GLAZED_TERRACOTTA = "green_glazed_terracotta";
    /**
     * @deprecated (1.12.0) use {@link #RED_GLAZED_TERRACOTTA} instead
     */
    @Deprecated
    String GLAZED_TERRACOTTA_RED = "glazedterracotta.red";
    String RED_GLAZED_TERRACOTTA = "red_glazed_terracotta";
    /**
     * @deprecated (1.12.0) use {@link #BLACK_GLAZED_TERRACOTTA} instead
     */
    @Deprecated
    String GLAZED_TERRACOTTA_BLACK = "glazedterracotta.black";
    String BLACK_GLAZED_TERRACOTTA = "black_glazed_terracotta";
    String WHITE_CONCRETE = "white_concrete"; //TODO: 1.20.10 flattening
    String CONCRETE = "concrete";
    String WHITE_CONCRETE_POWDER = "white_concrete_powder"; //TODO: 1.20.30 flattening
    String CONCRETE_POWDER = "concrete_powder";
    String CHEMISTRY_TABLE = "chemistry_table";
    String UNDERWATER_TORCH = "underwater_torch";
    String CHORUS_PLANT = "chorus_plant";
    String WHITE_STAINED_GLASS = "white_stained_glass"; //TODO: 1.20.20 flattening
    String STAINED_GLASS = "stained_glass";
    String ITEM_CAMERA = "item.camera";
    String PODZOL = "podzol";
    String ITEM_BEETROOT = "item.beetroot";
    String STONECUTTER = "stonecutter";
    String GLOWINGOBSIDIAN = "glowingobsidian";
    String NETHERREACTOR = "netherreactor";
    String INFO_UPDATE = "info_update";
    String INFO_UPDATE2 = "info_update2";
    String MOVING_BLOCK = "movingblock"; //TODO: 1.18.30 rename
    String MOVING_BLOCK_NEW = "moving_block";
    String OBSERVER = "observer";
    String STRUCTURE_BLOCK = "structure_block";
    String HARD_GLASS = "hard_glass";
    String HARD_WHITE_STAINED_GLASS = "hard_white_stained_glass"; //TODO: 1.20.60 flattening
    String HARD_STAINED_GLASS = "hard_stained_glass";
    String RESERVED6 = "reserved6";

    String PRISMARINE_STAIRS = "prismarine_stairs";
    String DARK_PRISMARINE_STAIRS = "dark_prismarine_stairs";
    String PRISMARINE_BRICKS_STAIRS = "prismarine_bricks_stairs";
    String STRIPPED_SPRUCE_LOG = "stripped_spruce_log";
    String STRIPPED_BIRCH_LOG = "stripped_birch_log";
    String STRIPPED_JUNGLE_LOG = "stripped_jungle_log";
    String STRIPPED_ACACIA_LOG = "stripped_acacia_log";
    String STRIPPED_DARK_OAK_LOG = "stripped_dark_oak_log";
    String STRIPPED_OAK_LOG = "stripped_oak_log";
    String BLUE_ICE = "blue_ice";
    String ELEMENT_1 = "element_1";
    String ELEMENT_2 = "element_2";
    String ELEMENT_3 = "element_3";
    String ELEMENT_4 = "element_4";
    String ELEMENT_5 = "element_5";
    String ELEMENT_6 = "element_6";
    String ELEMENT_7 = "element_7";
    String ELEMENT_8 = "element_8";
    String ELEMENT_9 = "element_9";
    String ELEMENT_10 = "element_10";
    String ELEMENT_11 = "element_11";
    String ELEMENT_12 = "element_12";
    String ELEMENT_13 = "element_13";
    String ELEMENT_14 = "element_14";
    String ELEMENT_15 = "element_15";
    String ELEMENT_16 = "element_16";
    String ELEMENT_17 = "element_17";
    String ELEMENT_18 = "element_18";
    String ELEMENT_19 = "element_19";
    String ELEMENT_20 = "element_20";
    String ELEMENT_21 = "element_21";
    String ELEMENT_22 = "element_22";
    String ELEMENT_23 = "element_23";
    String ELEMENT_24 = "element_24";
    String ELEMENT_25 = "element_25";
    String ELEMENT_26 = "element_26";
    String ELEMENT_27 = "element_27";
    String ELEMENT_28 = "element_28";
    String ELEMENT_29 = "element_29";
    String ELEMENT_30 = "element_30";
    String ELEMENT_31 = "element_31";
    String ELEMENT_32 = "element_32";
    String ELEMENT_33 = "element_33";
    String ELEMENT_34 = "element_34";
    String ELEMENT_35 = "element_35";
    String ELEMENT_36 = "element_36";
    String ELEMENT_37 = "element_37";
    String ELEMENT_38 = "element_38";
    String ELEMENT_39 = "element_39";
    String ELEMENT_40 = "element_40";
    String ELEMENT_41 = "element_41";
    String ELEMENT_42 = "element_42";
    String ELEMENT_43 = "element_43";
    String ELEMENT_44 = "element_44";
    String ELEMENT_45 = "element_45";
    String ELEMENT_46 = "element_46";
    String ELEMENT_47 = "element_47";
    String ELEMENT_48 = "element_48";
    String ELEMENT_49 = "element_49";
    String ELEMENT_50 = "element_50";
    String ELEMENT_51 = "element_51";
    String ELEMENT_52 = "element_52";
    String ELEMENT_53 = "element_53";
    String ELEMENT_54 = "element_54";
    String ELEMENT_55 = "element_55";
    String ELEMENT_56 = "element_56";
    String ELEMENT_57 = "element_57";
    String ELEMENT_58 = "element_58";
    String ELEMENT_59 = "element_59";
    String ELEMENT_60 = "element_60";
    String ELEMENT_61 = "element_61";
    String ELEMENT_62 = "element_62";
    String ELEMENT_63 = "element_63";
    String ELEMENT_64 = "element_64";
    String ELEMENT_65 = "element_65";
    String ELEMENT_66 = "element_66";
    String ELEMENT_67 = "element_67";
    String ELEMENT_68 = "element_68";
    String ELEMENT_69 = "element_69";
    String ELEMENT_70 = "element_70";
    String ELEMENT_71 = "element_71";
    String ELEMENT_72 = "element_72";
    String ELEMENT_73 = "element_73";
    String ELEMENT_74 = "element_74";
    String ELEMENT_75 = "element_75";
    String ELEMENT_76 = "element_76";
    String ELEMENT_77 = "element_77";
    String ELEMENT_78 = "element_78";
    String ELEMENT_79 = "element_79";
    String ELEMENT_80 = "element_80";
    String ELEMENT_81 = "element_81";
    String ELEMENT_82 = "element_82";
    String ELEMENT_83 = "element_83";
    String ELEMENT_84 = "element_84";
    String ELEMENT_85 = "element_85";
    String ELEMENT_86 = "element_86";
    String ELEMENT_87 = "element_87";
    String ELEMENT_88 = "element_88";
    String ELEMENT_89 = "element_89";
    String ELEMENT_90 = "element_90";
    String ELEMENT_91 = "element_91";
    String ELEMENT_92 = "element_92";
    String ELEMENT_93 = "element_93";
    String ELEMENT_94 = "element_94";
    String ELEMENT_95 = "element_95";
    String ELEMENT_96 = "element_96";
    String ELEMENT_97 = "element_97";
    String ELEMENT_98 = "element_98";
    String ELEMENT_99 = "element_99";
    String ELEMENT_100 = "element_100";
    String ELEMENT_101 = "element_101";
    String ELEMENT_102 = "element_102";
    String ELEMENT_103 = "element_103";
    String ELEMENT_104 = "element_104";
    String ELEMENT_105 = "element_105";
    String ELEMENT_106 = "element_106";
    String ELEMENT_107 = "element_107";
    String ELEMENT_108 = "element_108";
    String ELEMENT_109 = "element_109";
    String ELEMENT_110 = "element_110";
    String ELEMENT_111 = "element_111";
    String ELEMENT_112 = "element_112";
    String ELEMENT_113 = "element_113";
    String ELEMENT_114 = "element_114";
    String ELEMENT_115 = "element_115";
    String ELEMENT_116 = "element_116";
    String ELEMENT_117 = "element_117";
    String ELEMENT_118 = "element_118";
    String SEAGRASS = "seagrass";
    String TUBE_CORAL = "tube_coral"; //TODO: 1.20.0 flattening
    String CORAL = "coral";
    String TUBE_CORAL_BLOCK = "tube_coral_block"; //TODO: 1.21.0: flattening
    String CORAL_BLOCK = "coral_block";
    String TUBE_CORAL_FAN = "tube_coral_fan"; //TODO: 1.20.80 flattening
    String CORAL_FAN = "coral_fan";
    String DEAD_TUBE_CORAL_FAN = "dead_tube_coral_fan"; //TODO: 1.20.80 flattening
    String CORAL_FAN_DEAD = "coral_fan_dead";
    String TUBE_CORAL_WALL_FAN = "tube_coral_wall_fan"; //TODO: 1.21.20: flattening
    String CORAL_FAN_HANG = "coral_fan_hang";
    String BUBBLE_CORAL_WALL_FAN = "bubble_coral_wall_fan"; //TODO: 1.21.20: flattening
    String CORAL_FAN_HANG2 = "coral_fan_hang2";
    String HORN_CORAL_WALL_FAN = "horn_coral_wall_fan"; //TODO: 1.21.20: flattening
    String CORAL_FAN_HANG3 = "coral_fan_hang3";
    String ITEM_KELP = "item.kelp";
    String DRIED_KELP_BLOCK = "dried_kelp_block";
    String ACACIA_BUTTON = "acacia_button";
    String BIRCH_BUTTON = "birch_button";
    String DARK_OAK_BUTTON = "dark_oak_button";
    String JUNGLE_BUTTON = "jungle_button";
    String SPRUCE_BUTTON = "spruce_button";
    String ACACIA_TRAPDOOR = "acacia_trapdoor";
    String BIRCH_TRAPDOOR = "birch_trapdoor";
    String DARK_OAK_TRAPDOOR = "dark_oak_trapdoor";
    String JUNGLE_TRAPDOOR = "jungle_trapdoor";
    String SPRUCE_TRAPDOOR = "spruce_trapdoor";
    String ACACIA_PRESSURE_PLATE = "acacia_pressure_plate";
    String BIRCH_PRESSURE_PLATE = "birch_pressure_plate";
    String DARK_OAK_PRESSURE_PLATE = "dark_oak_pressure_plate";
    String JUNGLE_PRESSURE_PLATE = "jungle_pressure_plate";
    String SPRUCE_PRESSURE_PLATE = "spruce_pressure_plate";
    String CARVED_PUMPKIN = "carved_pumpkin";
    String SEA_PICKLE = "sea_pickle";
    String CONDUIT = "conduit";
    String AIR = "air";
    String TURTLE_EGG = "turtle_egg";
    String BUBBLE_COLUMN = "bubble_column";
    String BARRIER = "barrier";
    String END_STONE_BRICK_SLAB = "end_stone_brick_slab"; //TODO: 1.21.20 flattening
    String DOUBLE_STONE_SLAB3 = "double_stone_slab3"; //TODO: 1.19.0 rename
    String STONE_BLOCK_SLAB3 = "stone_block_slab3";
    String BAMBOO = "bamboo";
    String BAMBOO_SAPLING = "bamboo_sapling";
    String SCAFFOLDING = "scaffolding";
    String MOSSY_STONE_BRICK_SLAB = "mossy_stone_brick_slab"; //TODO: 1.21.20 flattening
    String DOUBLE_STONE_SLAB4 = "double_stone_slab4"; //TODO: 1.19.0 rename
    String STONE_BLOCK_SLAB4 = "stone_block_slab4";
    String END_STONE_BRICK_DOUBLE_SLAB = "end_stone_brick_double_slab"; //TODO: 1.21.20 flattening
    String REAL_DOUBLE_STONE_SLAB3 = "real_double_stone_slab3"; //TODO: 1.19.0 rename
    String DOUBLE_STONE_BLOCK_SLAB3 = "double_stone_block_slab3";
    String MOSSY_STONE_BRICK_DOUBLE_SLAB = "mossy_stone_brick_double_slab"; //TODO: 1.21.20 flattening
    String REAL_DOUBLE_STONE_SLAB4 = "real_double_stone_slab4"; //TODO: 1.19.0 rename
    String DOUBLE_STONE_BLOCK_SLAB4 = "double_stone_block_slab4";
    String GRANITE_STAIRS = "granite_stairs";
    String DIORITE_STAIRS = "diorite_stairs";
    String ANDESITE_STAIRS = "andesite_stairs";
    String POLISHED_GRANITE_STAIRS = "polished_granite_stairs";
    String POLISHED_DIORITE_STAIRS = "polished_diorite_stairs";
    String POLISHED_ANDESITE_STAIRS = "polished_andesite_stairs";
    String MOSSY_STONE_BRICK_STAIRS = "mossy_stone_brick_stairs";
    String SMOOTH_RED_SANDSTONE_STAIRS = "smooth_red_sandstone_stairs";
    String SMOOTH_SANDSTONE_STAIRS = "smooth_sandstone_stairs";
    String END_BRICK_STAIRS = "end_brick_stairs";
    String MOSSY_COBBLESTONE_STAIRS = "mossy_cobblestone_stairs";
    String NORMAL_STONE_STAIRS = "normal_stone_stairs";
    String SPRUCE_STANDING_SIGN = "spruce_standing_sign";
    String SPRUCE_WALL_SIGN = "spruce_wall_sign";
    String SMOOTH_STONE = "smooth_stone";
    String RED_NETHER_BRICK_STAIRS = "red_nether_brick_stairs";
    String SMOOTH_QUARTZ_STAIRS = "smooth_quartz_stairs";
    String BIRCH_STANDING_SIGN = "birch_standing_sign";
    String BIRCH_WALL_SIGN = "birch_wall_sign";
    String JUNGLE_STANDING_SIGN = "jungle_standing_sign";
    String JUNGLE_WALL_SIGN = "jungle_wall_sign";
    String ACACIA_STANDING_SIGN = "acacia_standing_sign";
    String ACACIA_WALL_SIGN = "acacia_wall_sign";
    String DARKOAK_STANDING_SIGN = "darkoak_standing_sign";
    String DARKOAK_WALL_SIGN = "darkoak_wall_sign";
    String LECTERN = "lectern";
    String GRINDSTONE = "grindstone";
    String BLAST_FURNACE = "blast_furnace";
    String STONECUTTER_BLOCK = "stonecutter_block";
    String SMOKER = "smoker";
    String LIT_SMOKER = "lit_smoker";
    String CARTOGRAPHY_TABLE = "cartography_table";
    String FLETCHING_TABLE = "fletching_table";
    String SMITHING_TABLE = "smithing_table";
    String BARREL = "barrel";
    String LOOM = "loom";
    String BELL = "bell"; //TODO: meta 31
    String SWEET_BERRY_BUSH = "sweet_berry_bush";
    String LANTERN = "lantern";
    String ITEM_CAMPFIRE = "item.campfire";
    String LAVA_CAULDRON = "lava_cauldron"; //TODO: 1.20.0 remove
    String JIGSAW = "jigsaw"; //TODO: meta 29
    String OAK_WOOD = "oak_wood"; //TODO: 1.20.70 flattening
    String WOOD = "wood";
    String COMPOSTER = "composter";
    String LIT_BLAST_FURNACE = "lit_blast_furnace";
    String LIGHT_BLOCK_0 = "light_block_0"; //TODO: 1.21.20 flattening
    String LIGHT_BLOCK = "light_block";
    String WITHER_ROSE = "wither_rose";
    String STICKY_PISTON_ARM_COLLISION = "stickypistonarmcollision"; //TODO: 1.18.30 rename
    String STICKY_PISTON_ARM_COLLISION_NEW = "sticky_piston_arm_collision";
    String BEE_NEST = "bee_nest";
    String BEEHIVE = "beehive";
    String HONEY_BLOCK = "honey_block";
    String HONEYCOMB_BLOCK = "honeycomb_block";
    String LODESTONE = "lodestone";
    String CRIMSON_ROOTS = "crimson_roots";
    String WARPED_ROOTS = "warped_roots";
    String CRIMSON_STEM = "crimson_stem";
    String WARPED_STEM = "warped_stem";
    String WARPED_WART_BLOCK = "warped_wart_block";
    String CRIMSON_FUNGUS = "crimson_fungus";
    String WARPED_FUNGUS = "warped_fungus";
    String SHROOMLIGHT = "shroomlight";
    String WEEPING_VINES = "weeping_vines";
    String CRIMSON_NYLIUM = "crimson_nylium";
    String WARPED_NYLIUM = "warped_nylium";
    String BASALT = "basalt";
    String POLISHED_BASALT = "polished_basalt";
    String SOUL_SOIL = "soul_soil";
    String SOUL_FIRE = "soul_fire";
    String ITEM_NETHER_SPROUTS = "item.nether_sprouts";
    String TARGET = "target";
    String STRIPPED_CRIMSON_STEM = "stripped_crimson_stem";
    String STRIPPED_WARPED_STEM = "stripped_warped_stem";
    String CRIMSON_PLANKS = "crimson_planks";
    String WARPED_PLANKS = "warped_planks";
    String ITEM_CRIMSON_DOOR = "item.crimson_door";
    String ITEM_WARPED_DOOR = "item.warped_door";
    String CRIMSON_TRAPDOOR = "crimson_trapdoor";
    String WARPED_TRAPDOOR = "warped_trapdoor";
    String CRIMSON_STANDING_SIGN = "crimson_standing_sign";
    String WARPED_STANDING_SIGN = "warped_standing_sign";
    String CRIMSON_WALL_SIGN = "crimson_wall_sign";
    String WARPED_WALL_SIGN = "warped_wall_sign";
    String CRIMSON_STAIRS = "crimson_stairs";
    String WARPED_STAIRS = "warped_stairs";
    String CRIMSON_FENCE = "crimson_fence";
    String WARPED_FENCE = "warped_fence";
    String CRIMSON_FENCE_GATE = "crimson_fence_gate";
    String WARPED_FENCE_GATE = "warped_fence_gate";
    String CRIMSON_BUTTON = "crimson_button";
    String WARPED_BUTTON = "warped_button";
    String CRIMSON_PRESSURE_PLATE = "crimson_pressure_plate";
    String WARPED_PRESSURE_PLATE = "warped_pressure_plate";
    String CRIMSON_SLAB = "crimson_slab";
    String WARPED_SLAB = "warped_slab";
    String CRIMSON_DOUBLE_SLAB = "crimson_double_slab";
    String WARPED_DOUBLE_SLAB = "warped_double_slab";
    String SOUL_TORCH = "soul_torch";
    String SOUL_LANTERN = "soul_lantern";
    String NETHERITE_BLOCK = "netherite_block";
    String ANCIENT_DEBRIS = "ancient_debris";
    String RESPAWN_ANCHOR = "respawn_anchor";
    String BLACKSTONE = "blackstone";
    String POLISHED_BLACKSTONE_BRICKS = "polished_blackstone_bricks";
    String POLISHED_BLACKSTONE_BRICK_STAIRS = "polished_blackstone_brick_stairs";
    String BLACKSTONE_STAIRS = "blackstone_stairs";
    String BLACKSTONE_WALL = "blackstone_wall";
    String POLISHED_BLACKSTONE_BRICK_WALL = "polished_blackstone_brick_wall";
    String CHISELED_POLISHED_BLACKSTONE = "chiseled_polished_blackstone";
    String CRACKED_POLISHED_BLACKSTONE_BRICKS = "cracked_polished_blackstone_bricks";
    String GILDED_BLACKSTONE = "gilded_blackstone";
    String BLACKSTONE_SLAB = "blackstone_slab";
    String BLACKSTONE_DOUBLE_SLAB = "blackstone_double_slab";
    String POLISHED_BLACKSTONE_BRICK_SLAB = "polished_blackstone_brick_slab";
    String POLISHED_BLACKSTONE_BRICK_DOUBLE_SLAB = "polished_blackstone_brick_double_slab";
    String ITEM_CHAIN = "item.chain";
    String TWISTING_VINES = "twisting_vines";
    String NETHER_GOLD_ORE = "nether_gold_ore";
    String CRYING_OBSIDIAN = "crying_obsidian";
    String ITEM_SOUL_CAMPFIRE = "item.soul_campfire";
    String POLISHED_BLACKSTONE = "polished_blackstone";
    String POLISHED_BLACKSTONE_STAIRS = "polished_blackstone_stairs";
    String POLISHED_BLACKSTONE_SLAB = "polished_blackstone_slab";
    String POLISHED_BLACKSTONE_DOUBLE_SLAB = "polished_blackstone_double_slab";
    String POLISHED_BLACKSTONE_PRESSURE_PLATE = "polished_blackstone_pressure_plate";
    String POLISHED_BLACKSTONE_BUTTON = "polished_blackstone_button";
    String POLISHED_BLACKSTONE_WALL = "polished_blackstone_wall";
    String WARPED_HYPHAE = "warped_hyphae";
    String CRIMSON_HYPHAE = "crimson_hyphae";
    String STRIPPED_CRIMSON_HYPHAE = "stripped_crimson_hyphae";
    String STRIPPED_WARPED_HYPHAE = "stripped_warped_hyphae";
    String CHISELED_NETHER_BRICKS = "chiseled_nether_bricks";
    String CRACKED_NETHER_BRICKS = "cracked_nether_bricks";
    String QUARTZ_BRICKS = "quartz_bricks";
    String UNKNOWN = "unknown";
    String POWDER_SNOW = "powder_snow";
    String SCULK_SENSOR = "sculk_sensor";
    String POINTED_DRIPSTONE = "pointed_dripstone";
    String COPPER_ORE = "copper_ore";
    String LIGHTNING_ROD = "lightning_rod";
    String CRAFTER = "crafter";
    String VAULT = "vault";
    String TRIAL_SPAWNER = "trial_spawner";
    String HEAVY_CORE = "heavy_core";
    String DRIPSTONE_BLOCK = "dripstone_block";
    String DIRT_WITH_ROOTS = "dirt_with_roots";
    String HANGING_ROOTS = "hanging_roots";
    String MOSS_BLOCK = "moss_block";
    String SPORE_BLOSSOM = "spore_blossom";
    String CAVE_VINES = "cave_vines";
    String BIG_DRIPLEAF = "big_dripleaf";
    String AZALEA_LEAVES = "azalea_leaves";
    String AZALEA_LEAVES_FLOWERED = "azalea_leaves_flowered";
    String CALCITE = "calcite";
    String AMETHYST_BLOCK = "amethyst_block";
    String BUDDING_AMETHYST = "budding_amethyst";
    String AMETHYST_CLUSTER = "amethyst_cluster";
    String LARGE_AMETHYST_BUD = "large_amethyst_bud";
    String MEDIUM_AMETHYST_BUD = "medium_amethyst_bud";
    String SMALL_AMETHYST_BUD = "small_amethyst_bud";
    String TUFF = "tuff";
    String TINTED_GLASS = "tinted_glass";
    String MOSS_CARPET = "moss_carpet";
    String SMALL_DRIPLEAF_BLOCK = "small_dripleaf_block";
    String AZALEA = "azalea";
    String FLOWERING_AZALEA = "flowering_azalea";
    String ITEM_GLOW_FRAME = "item.glow_frame";
    String COPPER_BLOCK = "copper_block";
    String EXPOSED_COPPER = "exposed_copper";
    String WEATHERED_COPPER = "weathered_copper";
    String OXIDIZED_COPPER = "oxidized_copper";
    String WAXED_COPPER = "waxed_copper";
    String WAXED_EXPOSED_COPPER = "waxed_exposed_copper";
    String WAXED_WEATHERED_COPPER = "waxed_weathered_copper";
    String CUT_COPPER = "cut_copper";
    String EXPOSED_CUT_COPPER = "exposed_cut_copper";
    String WEATHERED_CUT_COPPER = "weathered_cut_copper";
    String OXIDIZED_CUT_COPPER = "oxidized_cut_copper";
    String WAXED_CUT_COPPER = "waxed_cut_copper";
    String WAXED_EXPOSED_CUT_COPPER = "waxed_exposed_cut_copper";
    String WAXED_WEATHERED_CUT_COPPER = "waxed_weathered_cut_copper";
    String CUT_COPPER_STAIRS = "cut_copper_stairs";
    String EXPOSED_CUT_COPPER_STAIRS = "exposed_cut_copper_stairs";
    String WEATHERED_CUT_COPPER_STAIRS = "weathered_cut_copper_stairs";
    String OXIDIZED_CUT_COPPER_STAIRS = "oxidized_cut_copper_stairs";
    String WAXED_CUT_COPPER_STAIRS = "waxed_cut_copper_stairs";
    String WAXED_EXPOSED_CUT_COPPER_STAIRS = "waxed_exposed_cut_copper_stairs";
    String WAXED_WEATHERED_CUT_COPPER_STAIRS = "waxed_weathered_cut_copper_stairs";
    String CUT_COPPER_SLAB = "cut_copper_slab";
    String EXPOSED_CUT_COPPER_SLAB = "exposed_cut_copper_slab";
    String WEATHERED_CUT_COPPER_SLAB = "weathered_cut_copper_slab";
    String OXIDIZED_CUT_COPPER_SLAB = "oxidized_cut_copper_slab";
    String WAXED_CUT_COPPER_SLAB = "waxed_cut_copper_slab";
    String WAXED_EXPOSED_CUT_COPPER_SLAB = "waxed_exposed_cut_copper_slab";
    String WAXED_WEATHERED_CUT_COPPER_SLAB = "waxed_weathered_cut_copper_slab";
    String DOUBLE_CUT_COPPER_SLAB = "double_cut_copper_slab";
    String EXPOSED_DOUBLE_CUT_COPPER_SLAB = "exposed_double_cut_copper_slab";
    String WEATHERED_DOUBLE_CUT_COPPER_SLAB = "weathered_double_cut_copper_slab";
    String OXIDIZED_DOUBLE_CUT_COPPER_SLAB = "oxidized_double_cut_copper_slab";
    String WAXED_DOUBLE_CUT_COPPER_SLAB = "waxed_double_cut_copper_slab";
    String WAXED_EXPOSED_DOUBLE_CUT_COPPER_SLAB = "waxed_exposed_double_cut_copper_slab";
    String WAXED_WEATHERED_DOUBLE_CUT_COPPER_SLAB = "waxed_weathered_double_cut_copper_slab";
    String CAVE_VINES_BODY_WITH_BERRIES = "cave_vines_body_with_berries";
    String CAVE_VINES_HEAD_WITH_BERRIES = "cave_vines_head_with_berries";
    String SMOOTH_BASALT = "smooth_basalt";
    String DEEPSLATE = "deepslate";
    String COBBLED_DEEPSLATE = "cobbled_deepslate";
    String COBBLED_DEEPSLATE_SLAB = "cobbled_deepslate_slab";
    String COBBLED_DEEPSLATE_STAIRS = "cobbled_deepslate_stairs";
    String COBBLED_DEEPSLATE_WALL = "cobbled_deepslate_wall";
    String POLISHED_DEEPSLATE = "polished_deepslate";
    String POLISHED_DEEPSLATE_SLAB = "polished_deepslate_slab";
    String POLISHED_DEEPSLATE_STAIRS = "polished_deepslate_stairs";
    String POLISHED_DEEPSLATE_WALL = "polished_deepslate_wall";
    String DEEPSLATE_TILES = "deepslate_tiles";
    String DEEPSLATE_TILE_SLAB = "deepslate_tile_slab";
    String DEEPSLATE_TILE_STAIRS = "deepslate_tile_stairs";
    String DEEPSLATE_TILE_WALL = "deepslate_tile_wall";
    String DEEPSLATE_BRICKS = "deepslate_bricks";
    String DEEPSLATE_BRICK_SLAB = "deepslate_brick_slab";
    String DEEPSLATE_BRICK_STAIRS = "deepslate_brick_stairs";
    String DEEPSLATE_BRICK_WALL = "deepslate_brick_wall";
    String CHISELED_DEEPSLATE = "chiseled_deepslate";
    String COBBLED_DEEPSLATE_DOUBLE_SLAB = "cobbled_deepslate_double_slab";
    String POLISHED_DEEPSLATE_DOUBLE_SLAB = "polished_deepslate_double_slab";
    String DEEPSLATE_TILE_DOUBLE_SLAB = "deepslate_tile_double_slab";
    String DEEPSLATE_BRICK_DOUBLE_SLAB = "deepslate_brick_double_slab";
    String DEEPSLATE_LAPIS_ORE = "deepslate_lapis_ore";
    String DEEPSLATE_IRON_ORE = "deepslate_iron_ore";
    String DEEPSLATE_GOLD_ORE = "deepslate_gold_ore";
    String DEEPSLATE_REDSTONE_ORE = "deepslate_redstone_ore";
    String LIT_DEEPSLATE_REDSTONE_ORE = "lit_deepslate_redstone_ore";
    String DEEPSLATE_DIAMOND_ORE = "deepslate_diamond_ore";
    String DEEPSLATE_COAL_ORE = "deepslate_coal_ore";
    String DEEPSLATE_EMERALD_ORE = "deepslate_emerald_ore";
    String DEEPSLATE_COPPER_ORE = "deepslate_copper_ore";
    String CRACKED_DEEPSLATE_TILES = "cracked_deepslate_tiles";
    String CRACKED_DEEPSLATE_BRICKS = "cracked_deepslate_bricks";
    String GLOW_LICHEN = "glow_lichen";
    String CANDLE = "candle";
    String WHITE_CANDLE = "white_candle";
    String ORANGE_CANDLE = "orange_candle";
    String MAGENTA_CANDLE = "magenta_candle";
    String LIGHT_BLUE_CANDLE = "light_blue_candle";
    String YELLOW_CANDLE = "yellow_candle";
    String LIME_CANDLE = "lime_candle";
    String PINK_CANDLE = "pink_candle";
    String GRAY_CANDLE = "gray_candle";
    String LIGHT_GRAY_CANDLE = "light_gray_candle";
    String CYAN_CANDLE = "cyan_candle";
    String PURPLE_CANDLE = "purple_candle";
    String BLUE_CANDLE = "blue_candle";
    String BROWN_CANDLE = "brown_candle";
    String GREEN_CANDLE = "green_candle";
    String RED_CANDLE = "red_candle";
    String BLACK_CANDLE = "black_candle";
    String CANDLE_CAKE = "candle_cake";
    String WHITE_CANDLE_CAKE = "white_candle_cake";
    String ORANGE_CANDLE_CAKE = "orange_candle_cake";
    String MAGENTA_CANDLE_CAKE = "magenta_candle_cake";
    String LIGHT_BLUE_CANDLE_CAKE = "light_blue_candle_cake";
    String YELLOW_CANDLE_CAKE = "yellow_candle_cake";
    String LIME_CANDLE_CAKE = "lime_candle_cake";
    String PINK_CANDLE_CAKE = "pink_candle_cake";
    String GRAY_CANDLE_CAKE = "gray_candle_cake";
    String LIGHT_GRAY_CANDLE_CAKE = "light_gray_candle_cake";
    String CYAN_CANDLE_CAKE = "cyan_candle_cake";
    String PURPLE_CANDLE_CAKE = "purple_candle_cake";
    String BLUE_CANDLE_CAKE = "blue_candle_cake";
    String BROWN_CANDLE_CAKE = "brown_candle_cake";
    String GREEN_CANDLE_CAKE = "green_candle_cake";
    String RED_CANDLE_CAKE = "red_candle_cake";
    String BLACK_CANDLE_CAKE = "black_candle_cake";
    String WAXED_OXIDIZED_COPPER = "waxed_oxidized_copper";
    String WAXED_OXIDIZED_CUT_COPPER = "waxed_oxidized_cut_copper";
    String WAXED_OXIDIZED_CUT_COPPER_STAIRS = "waxed_oxidized_cut_copper_stairs";
    String WAXED_OXIDIZED_CUT_COPPER_SLAB = "waxed_oxidized_cut_copper_slab";
    String WAXED_OXIDIZED_DOUBLE_CUT_COPPER_SLAB = "waxed_oxidized_double_cut_copper_slab";
    String RAW_IRON_BLOCK = "raw_iron_block";
    String RAW_COPPER_BLOCK = "raw_copper_block";
    String RAW_GOLD_BLOCK = "raw_gold_block";
    String INFESTED_DEEPSLATE = "infested_deepslate";
    String SCULK = "sculk";
    String SCULK_VEIN = "sculk_vein";
    String SCULK_CATALYST = "sculk_catalyst";
    String SCULK_SHRIEKER = "sculk_shrieker";
    String CLIENT_REQUEST_PLACEHOLDER_BLOCK = "client_request_placeholder_block";
    String REINFORCED_DEEPSLATE = "reinforced_deepslate";
    /**
     * @deprecated use {@link #REINFORCED_DEEPSLATE} instead
     */
    @Deprecated
    String MYSTERIOUS_FRAME = "mysterious_frame";
    /**
     * @deprecated removed
     */
    @Deprecated
    String MYSTERIOUS_FRAME_SLOT = "mysterious_frame_slot";
    String FROG_SPAWN = "frog_spawn";
    String PEARLESCENT_FROGLIGHT = "pearlescent_froglight";
    String VERDANT_FROGLIGHT = "verdant_froglight";
    String OCHRE_FROGLIGHT = "ochre_froglight";
    String MANGROVE_LEAVES = "mangrove_leaves";
    String MUD = "mud";
    String MANGROVE_PROPAGULE = "mangrove_propagule";
    String MUD_BRICKS = "mud_bricks";
    String PACKED_MUD = "packed_mud";
    String MUD_BRICK_SLAB = "mud_brick_slab";
    String MUD_BRICK_DOUBLE_SLAB = "mud_brick_double_slab";
    String MUD_BRICK_STAIRS = "mud_brick_stairs";
    String MUD_BRICK_WALL = "mud_brick_wall";
    String MANGROVE_ROOTS = "mangrove_roots";
    String MUDDY_MANGROVE_ROOTS = "muddy_mangrove_roots";
    String MANGROVE_LOG = "mangrove_log";
    String STRIPPED_MANGROVE_LOG = "stripped_mangrove_log";
    String MANGROVE_PLANKS = "mangrove_planks";
    String MANGROVE_BUTTON = "mangrove_button";
    String MANGROVE_STAIRS = "mangrove_stairs";
    String MANGROVE_SLAB = "mangrove_slab";
    String MANGROVE_PRESSURE_PLATE = "mangrove_pressure_plate";
    String MANGROVE_FENCE = "mangrove_fence";
    String MANGROVE_FENCE_GATE = "mangrove_fence_gate";
    String ITEM_MANGROVE_DOOR = "item.mangrove_door";
    String MANGROVE_STANDING_SIGN = "mangrove_standing_sign";
    String MANGROVE_WALL_SIGN = "mangrove_wall_sign";
    String MANGROVE_TRAPDOOR = "mangrove_trapdoor";
    String MANGROVE_WOOD = "mangrove_wood";
    String STRIPPED_MANGROVE_WOOD = "stripped_mangrove_wood";
    String MANGROVE_DOUBLE_SLAB = "mangrove_double_slab";
    String OAK_HANGING_SIGN = "oak_hanging_sign";
    String SPRUCE_HANGING_SIGN = "spruce_hanging_sign";
    String BIRCH_HANGING_SIGN = "birch_hanging_sign";
    String JUNGLE_HANGING_SIGN = "jungle_hanging_sign";
    String ACACIA_HANGING_SIGN = "acacia_hanging_sign";
    String DARK_OAK_HANGING_SIGN = "dark_oak_hanging_sign";
    String CRIMSON_HANGING_SIGN = "crimson_hanging_sign";
    String WARPED_HANGING_SIGN = "warped_hanging_sign";
    String MANGROVE_HANGING_SIGN = "mangrove_hanging_sign";
    String BAMBOO_MOSAIC = "bamboo_mosaic";
    String BAMBOO_PLANKS = "bamboo_planks";
    String BAMBOO_BUTTON = "bamboo_button";
    String BAMBOO_STAIRS = "bamboo_stairs";
    String BAMBOO_SLAB = "bamboo_slab";
    String BAMBOO_PRESSURE_PLATE = "bamboo_pressure_plate";
    String BAMBOO_FENCE = "bamboo_fence";
    String BAMBOO_FENCE_GATE = "bamboo_fence_gate";
    String BAMBOO_DOOR = "bamboo_door";
    String BAMBOO_STANDING_SIGN = "bamboo_standing_sign";
    String BAMBOO_WALL_SIGN = "bamboo_wall_sign";
    String BAMBOO_TRAPDOOR = "bamboo_trapdoor";
    String BAMBOO_DOUBLE_SLAB = "bamboo_double_slab";
    String BAMBOO_HANGING_SIGN = "bamboo_hanging_sign";
    String BAMBOO_MOSAIC_STAIRS = "bamboo_mosaic_stairs";
    String BAMBOO_MOSAIC_SLAB = "bamboo_mosaic_slab";
    String BAMBOO_MOSAIC_DOUBLE_SLAB = "bamboo_mosaic_double_slab";
    String CHISELED_BOOKSHELF = "chiseled_bookshelf";
    String BAMBOO_BLOCK = "bamboo_block";
    String STRIPPED_BAMBOO_BLOCK = "stripped_bamboo_block";
    String SUSPICIOUS_SAND = "suspicious_sand";
    String CHERRY_BUTTON = "cherry_button";
    String CHERRY_DOOR = "cherry_door";
    String CHERRY_FENCE = "cherry_fence";
    String CHERRY_FENCE_GATE = "cherry_fence_gate";
    String CHERRY_HANGING_SIGN = "cherry_hanging_sign";
    String STRIPPED_CHERRY_LOG = "stripped_cherry_log";
    String CHERRY_LOG = "cherry_log";
    String CHERRY_PLANKS = "cherry_planks";
    String CHERRY_PRESSURE_PLATE = "cherry_pressure_plate";
    String CHERRY_SLAB = "cherry_slab";
    String CHERRY_DOUBLE_SLAB = "cherry_double_slab";
    String CHERRY_STAIRS = "cherry_stairs";
    String CHERRY_STANDING_SIGN = "cherry_standing_sign";
    String CHERRY_TRAPDOOR = "cherry_trapdoor";
    String CHERRY_WALL_SIGN = "cherry_wall_sign";
    String STRIPPED_CHERRY_WOOD = "stripped_cherry_wood";
    String CHERRY_WOOD = "cherry_wood";
    String CHERRY_SAPLING = "cherry_sapling";
    String CHERRY_LEAVES = "cherry_leaves";
    String PINK_PETALS = "pink_petals";

    String DECORATED_POT = "decorated_pot";
    String LIGHT_GRAY_WOOL = "light_gray_wool";
    String GRAY_WOOL = "gray_wool";
    String BLACK_WOOL = "black_wool";
    String BROWN_WOOL = "brown_wool";
    String RED_WOOL = "red_wool";
    String ORANGE_WOOL = "orange_wool";
    String YELLOW_WOOL = "yellow_wool";
    String LIME_WOOL = "lime_wool";
    String GREEN_WOOL = "green_wool";
    String CYAN_WOOL = "cyan_wool";
    String LIGHT_BLUE_WOOL = "light_blue_wool";
    String BLUE_WOOL = "blue_wool";
    String PURPLE_WOOL = "purple_wool";
    String MAGENTA_WOOL = "magenta_wool";
    String PINK_WOOL = "pink_wool";
    String TORCHFLOWER_CROP = "torchflower_crop";
    String TORCHFLOWER = "torchflower";
    String SPRUCE_LOG = "spruce_log";
    String BIRCH_LOG = "birch_log";
    String JUNGLE_LOG = "jungle_log";
    String DARK_OAK_LOG = "dark_oak_log";
    String SUSPICIOUS_GRAVEL = "suspicious_gravel";
    String PITCHER_CROP = "pitcher_crop";
    String ACACIA_FENCE = "acacia_fence";
    String BIRCH_FENCE = "birch_fence";
    String DARK_OAK_FENCE = "dark_oak_fence";
    String JUNGLE_FENCE = "jungle_fence";
    String SPRUCE_FENCE = "spruce_fence";
    String CALIBRATED_SCULK_SENSOR = "calibrated_sculk_sensor";
    String BRAIN_CORAL = "brain_coral";
    String BUBBLE_CORAL = "bubble_coral";
    String FIRE_CORAL = "fire_coral";
    String HORN_CORAL = "horn_coral";
    String DEAD_TUBE_CORAL = "dead_tube_coral";
    String DEAD_BRAIN_CORAL = "dead_brain_coral";
    String DEAD_BUBBLE_CORAL = "dead_bubble_coral";
    String DEAD_FIRE_CORAL = "dead_fire_coral";
    String DEAD_HORN_CORAL = "dead_horn_coral";
    String GRANITE = "granite";
    String POLISHED_GRANITE = "polished_granite";
    String DIORITE = "diorite";
    String POLISHED_DIORITE = "polished_diorite";
    String ANDESITE = "andesite";
    String POLISHED_ANDESITE = "polished_andesite";
    String SNIFFER_EGG = "sniffer_egg";
    String ORANGE_CARPET = "orange_carpet";
    String MAGENTA_CARPET = "magenta_carpet";
    String LIGHT_BLUE_CARPET = "light_blue_carpet";
    String YELLOW_CARPET = "yellow_carpet";
    String LIME_CARPET = "lime_carpet";
    String PINK_CARPET = "pink_carpet";
    String GRAY_CARPET = "gray_carpet";
    String LIGHT_GRAY_CARPET = "light_gray_carpet";
    String CYAN_CARPET = "cyan_carpet";
    String PURPLE_CARPET = "purple_carpet";
    String BLUE_CARPET = "blue_carpet";
    String BROWN_CARPET = "brown_carpet";
    String GREEN_CARPET = "green_carpet";
    String RED_CARPET = "red_carpet";
    String BLACK_CARPET = "black_carpet";
    String PITCHER_PLANT = "pitcher_plant";
    String ORANGE_SHULKER_BOX = "orange_shulker_box";
    String MAGENTA_SHULKER_BOX = "magenta_shulker_box";
    String LIGHT_BLUE_SHULKER_BOX = "light_blue_shulker_box";
    String YELLOW_SHULKER_BOX = "yellow_shulker_box";
    String LIME_SHULKER_BOX = "lime_shulker_box";
    String PINK_SHULKER_BOX = "pink_shulker_box";
    String GRAY_SHULKER_BOX = "gray_shulker_box";
    String LIGHT_GRAY_SHULKER_BOX = "light_gray_shulker_box";
    String CYAN_SHULKER_BOX = "cyan_shulker_box";
    String PURPLE_SHULKER_BOX = "purple_shulker_box";
    String BLUE_SHULKER_BOX = "blue_shulker_box";
    String BROWN_SHULKER_BOX = "brown_shulker_box";
    String GREEN_SHULKER_BOX = "green_shulker_box";
    String RED_SHULKER_BOX = "red_shulker_box";
    String BLACK_SHULKER_BOX = "black_shulker_box";
    String ORANGE_CONCRETE = "orange_concrete";
    String MAGENTA_CONCRETE = "magenta_concrete";
    String LIGHT_BLUE_CONCRETE = "light_blue_concrete";
    String YELLOW_CONCRETE = "yellow_concrete";
    String LIME_CONCRETE = "lime_concrete";
    String PINK_CONCRETE = "pink_concrete";
    String GRAY_CONCRETE = "gray_concrete";
    String LIGHT_GRAY_CONCRETE = "light_gray_concrete";
    String CYAN_CONCRETE = "cyan_concrete";
    String PURPLE_CONCRETE = "purple_concrete";
    String BLUE_CONCRETE = "blue_concrete";
    String BROWN_CONCRETE = "brown_concrete";
    String GREEN_CONCRETE = "green_concrete";
    String RED_CONCRETE = "red_concrete";
    String BLACK_CONCRETE = "black_concrete";
    String ORANGE_STAINED_GLASS_PANE = "orange_stained_glass_pane";
    String MAGENTA_STAINED_GLASS_PANE = "magenta_stained_glass_pane";
    String LIGHT_BLUE_STAINED_GLASS_PANE = "light_blue_stained_glass_pane";
    String YELLOW_STAINED_GLASS_PANE = "yellow_stained_glass_pane";
    String LIME_STAINED_GLASS_PANE = "lime_stained_glass_pane";
    String PINK_STAINED_GLASS_PANE = "pink_stained_glass_pane";
    String GRAY_STAINED_GLASS_PANE = "gray_stained_glass_pane";
    String LIGHT_GRAY_STAINED_GLASS_PANE = "light_gray_stained_glass_pane";
    String CYAN_STAINED_GLASS_PANE = "cyan_stained_glass_pane";
    String PURPLE_STAINED_GLASS_PANE = "purple_stained_glass_pane";
    String BLUE_STAINED_GLASS_PANE = "blue_stained_glass_pane";
    String BROWN_STAINED_GLASS_PANE = "brown_stained_glass_pane";
    String GREEN_STAINED_GLASS_PANE = "green_stained_glass_pane";
    String RED_STAINED_GLASS_PANE = "red_stained_glass_pane";
    String BLACK_STAINED_GLASS_PANE = "black_stained_glass_pane";
    String HARD_ORANGE_STAINED_GLASS_PANE = "hard_orange_stained_glass_pane";
    String HARD_MAGENTA_STAINED_GLASS_PANE = "hard_magenta_stained_glass_pane";
    String HARD_LIGHT_BLUE_STAINED_GLASS_PANE = "hard_light_blue_stained_glass_pane";
    String HARD_YELLOW_STAINED_GLASS_PANE = "hard_yellow_stained_glass_pane";
    String HARD_LIME_STAINED_GLASS_PANE = "hard_lime_stained_glass_pane";
    String HARD_PINK_STAINED_GLASS_PANE = "hard_pink_stained_glass_pane";
    String HARD_GRAY_STAINED_GLASS_PANE = "hard_gray_stained_glass_pane";
    String HARD_LIGHT_GRAY_STAINED_GLASS_PANE = "hard_light_gray_stained_glass_pane";
    String HARD_CYAN_STAINED_GLASS_PANE = "hard_cyan_stained_glass_pane";
    String HARD_PURPLE_STAINED_GLASS_PANE = "hard_purple_stained_glass_pane";
    String HARD_BLUE_STAINED_GLASS_PANE = "hard_blue_stained_glass_pane";
    String HARD_BROWN_STAINED_GLASS_PANE = "hard_brown_stained_glass_pane";
    String HARD_GREEN_STAINED_GLASS_PANE = "hard_green_stained_glass_pane";
    String HARD_RED_STAINED_GLASS_PANE = "hard_red_stained_glass_pane";
    String HARD_BLACK_STAINED_GLASS_PANE = "hard_black_stained_glass_pane";
    String ORANGE_STAINED_GLASS = "orange_stained_glass";
    String MAGENTA_STAINED_GLASS = "magenta_stained_glass";
    String LIGHT_BLUE_STAINED_GLASS = "light_blue_stained_glass";
    String YELLOW_STAINED_GLASS = "yellow_stained_glass";
    String LIME_STAINED_GLASS = "lime_stained_glass";
    String PINK_STAINED_GLASS = "pink_stained_glass";
    String GRAY_STAINED_GLASS = "gray_stained_glass";
    String LIGHT_GRAY_STAINED_GLASS = "light_gray_stained_glass";
    String CYAN_STAINED_GLASS = "cyan_stained_glass";
    String PURPLE_STAINED_GLASS = "purple_stained_glass";
    String BLUE_STAINED_GLASS = "blue_stained_glass";
    String BROWN_STAINED_GLASS = "brown_stained_glass";
    String GREEN_STAINED_GLASS = "green_stained_glass";
    String RED_STAINED_GLASS = "red_stained_glass";
    String BLACK_STAINED_GLASS = "black_stained_glass";
    String HARD_ORANGE_STAINED_GLASS = "hard_orange_stained_glass";
    String HARD_MAGENTA_STAINED_GLASS = "hard_magenta_stained_glass";
    String HARD_LIGHT_BLUE_STAINED_GLASS = "hard_light_blue_stained_glass";
    String HARD_YELLOW_STAINED_GLASS = "hard_yellow_stained_glass";
    String HARD_LIME_STAINED_GLASS = "hard_lime_stained_glass";
    String HARD_PINK_STAINED_GLASS = "hard_pink_stained_glass";
    String HARD_GRAY_STAINED_GLASS = "hard_gray_stained_glass";
    String HARD_LIGHT_GRAY_STAINED_GLASS = "hard_light_gray_stained_glass";
    String HARD_CYAN_STAINED_GLASS = "hard_cyan_stained_glass";
    String HARD_PURPLE_STAINED_GLASS = "hard_purple_stained_glass";
    String HARD_BLUE_STAINED_GLASS = "hard_blue_stained_glass";
    String HARD_BROWN_STAINED_GLASS = "hard_brown_stained_glass";
    String HARD_GREEN_STAINED_GLASS = "hard_green_stained_glass";
    String HARD_RED_STAINED_GLASS = "hard_red_stained_glass";
    String HARD_BLACK_STAINED_GLASS = "hard_black_stained_glass";

    String ORANGE_CONCRETE_POWDER = "orange_concrete_powder";
    String MAGENTA_CONCRETE_POWDER = "magenta_concrete_powder";
    String LIGHT_BLUE_CONCRETE_POWDER = "light_blue_concrete_powder";
    String YELLOW_CONCRETE_POWDER = "yellow_concrete_powder";
    String LIME_CONCRETE_POWDER = "lime_concrete_powder";
    String PINK_CONCRETE_POWDER = "pink_concrete_powder";
    String GRAY_CONCRETE_POWDER = "gray_concrete_powder";
    String LIGHT_GRAY_CONCRETE_POWDER = "light_gray_concrete_powder";
    String CYAN_CONCRETE_POWDER = "cyan_concrete_powder";
    String PURPLE_CONCRETE_POWDER = "purple_concrete_powder";
    String BLUE_CONCRETE_POWDER = "blue_concrete_powder";
    String BROWN_CONCRETE_POWDER = "brown_concrete_powder";
    String GREEN_CONCRETE_POWDER = "green_concrete_powder";
    String RED_CONCRETE_POWDER = "red_concrete_powder";
    String BLACK_CONCRETE_POWDER = "black_concrete_powder";
    String ORANGE_TERRACOTTA = "orange_terracotta";
    String MAGENTA_TERRACOTTA = "magenta_terracotta";
    String LIGHT_BLUE_TERRACOTTA = "light_blue_terracotta";
    String YELLOW_TERRACOTTA = "yellow_terracotta";
    String LIME_TERRACOTTA = "lime_terracotta";
    String PINK_TERRACOTTA = "pink_terracotta";
    String GRAY_TERRACOTTA = "gray_terracotta";
    String LIGHT_GRAY_TERRACOTTA = "light_gray_terracotta";
    String CYAN_TERRACOTTA = "cyan_terracotta";
    String PURPLE_TERRACOTTA = "purple_terracotta";
    String BLUE_TERRACOTTA = "blue_terracotta";
    String BROWN_TERRACOTTA = "brown_terracotta";
    String GREEN_TERRACOTTA = "green_terracotta";
    String RED_TERRACOTTA = "red_terracotta";
    String BLACK_TERRACOTTA = "black_terracotta";
    String SPRUCE_PLANKS = "spruce_planks";
    String BIRCH_PLANKS = "birch_planks";
    String JUNGLE_PLANKS = "jungle_planks";
    String ACACIA_PLANKS = "acacia_planks";
    String DARK_OAK_PLANKS = "dark_oak_planks";
    String TUFF_SLAB = "tuff_slab";
    String TUFF_DOUBLE_SLAB = "tuff_double_slab";
    String TUFF_STAIRS = "tuff_stairs";
    String TUFF_WALL = "tuff_wall";
    String POLISHED_TUFF = "polished_tuff";
    String POLISHED_TUFF_SLAB = "polished_tuff_slab";
    String POLISHED_TUFF_DOUBLE_SLAB = "polished_tuff_double_slab";
    String POLISHED_TUFF_STAIRS = "polished_tuff_stairs";
    String POLISHED_TUFF_WALL = "polished_tuff_wall";
    String CHISELED_TUFF = "chiseled_tuff";
    String TUFF_BRICKS = "tuff_bricks";
    String TUFF_BRICK_SLAB = "tuff_brick_slab";
    String TUFF_BRICK_DOUBLE_SLAB = "tuff_brick_double_slab";
    String TUFF_BRICK_STAIRS = "tuff_brick_stairs";
    String TUFF_BRICK_WALL = "tuff_brick_wall";
    String CHISELED_TUFF_BRICKS = "chiseled_tuff_bricks";
    String CHISELED_COPPER = "chiseled_copper";
    String EXPOSED_CHISELED_COPPER = "exposed_chiseled_copper";
    String WEATHERED_CHISELED_COPPER = "weathered_chiseled_copper";
    String OXIDIZED_CHISELED_COPPER = "oxidized_chiseled_copper";
    String WAXED_CHISELED_COPPER = "waxed_chiseled_copper";
    String WAXED_EXPOSED_CHISELED_COPPER = "waxed_exposed_chiseled_copper";
    String WAXED_OXIDIZED_CHISELED_COPPER = "waxed_oxidized_chiseled_copper";
    String WAXED_WEATHERED_CHISELED_COPPER = "waxed_weathered_chiseled_copper";
    String COPPER_GRATE = "copper_grate";
    String EXPOSED_COPPER_GRATE = "exposed_copper_grate";
    String WEATHERED_COPPER_GRATE = "weathered_copper_grate";
    String OXIDIZED_COPPER_GRATE = "oxidized_copper_grate";
    String WAXED_COPPER_GRATE = "waxed_copper_grate";
    String WAXED_EXPOSED_COPPER_GRATE = "waxed_exposed_copper_grate";
    String WAXED_WEATHERED_COPPER_GRATE = "waxed_weathered_copper_grate";
    String WAXED_OXIDIZED_COPPER_GRATE = "waxed_oxidized_copper_grate";
    String COPPER_BULB = "copper_bulb";
    String EXPOSED_COPPER_BULB = "exposed_copper_bulb";
    String WEATHERED_COPPER_BULB = "weathered_copper_bulb";
    String OXIDIZED_COPPER_BULB = "oxidized_copper_bulb";
    String WAXED_COPPER_BULB = "waxed_copper_bulb";
    String WAXED_EXPOSED_COPPER_BULB = "waxed_exposed_copper_bulb";
    String WAXED_WEATHERED_COPPER_BULB = "waxed_weathered_copper_bulb";
    String WAXED_OXIDIZED_COPPER_BULB = "waxed_oxidized_copper_bulb";
    String COPPER_DOOR = "copper_door";
    String EXPOSED_COPPER_DOOR = "exposed_copper_door";
    String WEATHERED_COPPER_DOOR = "weathered_copper_door";
    String OXIDIZED_COPPER_DOOR = "oxidized_copper_door";
    String WAXED_COPPER_DOOR = "waxed_copper_door";
    String WAXED_EXPOSED_COPPER_DOOR = "waxed_exposed_copper_door";
    String WAXED_WEATHERED_COPPER_DOOR = "waxed_weathered_copper_door";
    String WAXED_OXIDIZED_COPPER_DOOR = "waxed_oxidized_copper_door";
    String COPPER_TRAPDOOR = "copper_trapdoor";
    String EXPOSED_COPPER_TRAPDOOR = "exposed_copper_trapdoor";
    String WEATHERED_COPPER_TRAPDOOR = "weathered_copper_trapdoor";
    String OXIDIZED_COPPER_TRAPDOOR = "oxidized_copper_trapdoor";
    String WAXED_COPPER_TRAPDOOR = "waxed_copper_trapdoor";
    String WAXED_EXPOSED_COPPER_TRAPDOOR = "waxed_exposed_copper_trapdoor";
    String WAXED_WEATHERED_COPPER_TRAPDOOR = "waxed_weathered_copper_trapdoor";
    String WAXED_OXIDIZED_COPPER_TRAPDOOR = "waxed_oxidized_copper_trapdoor";
    String SPRUCE_LEAVES = "spruce_leaves";
    String BIRCH_LEAVES = "birch_leaves";
    String JUNGLE_LEAVES = "jungle_leaves";
    String DARK_OAK_LEAVES = "dark_oak_leaves";
    String SPRUCE_SLAB = "spruce_slab";
    String BIRCH_SLAB = "birch_slab";
    String JUNGLE_SLAB = "jungle_slab";
    String ACACIA_SLAB = "acacia_slab";
    String DARK_OAK_SLAB = "dark_oak_slab";
    String SPRUCE_DOUBLE_SLAB = "spruce_double_slab";
    String BIRCH_DOUBLE_SLAB = "birch_double_slab";
    String JUNGLE_DOUBLE_SLAB = "jungle_double_slab";
    String ACACIA_DOUBLE_SLAB = "acacia_double_slab";
    String DARK_OAK_DOUBLE_SLAB = "dark_oak_double_slab";
    String SPRUCE_WOOD = "spruce_wood";
    String BIRCH_WOOD = "birch_wood";
    String JUNGLE_WOOD = "jungle_wood";
    String ACACIA_WOOD = "acacia_wood";
    String DARK_OAK_WOOD = "dark_oak_wood";
    String STRIPPED_OAK_WOOD = "stripped_oak_wood";
    String STRIPPED_SPRUCE_WOOD = "stripped_spruce_wood";
    String STRIPPED_BIRCH_WOOD = "stripped_birch_wood";
    String STRIPPED_JUNGLE_WOOD = "stripped_jungle_wood";
    String STRIPPED_ACACIA_WOOD = "stripped_acacia_wood";
    String STRIPPED_DARK_OAK_WOOD = "stripped_dark_oak_wood";
    String SPRUCE_SAPLING = "spruce_sapling";
    String BIRCH_SAPLING = "birch_sapling";
    String JUNGLE_SAPLING = "jungle_sapling";
    String ACACIA_SAPLING = "acacia_sapling";
    String DARK_OAK_SAPLING = "dark_oak_sapling";
    String BLUE_ORCHID = "blue_orchid";
    String ALLIUM = "allium";
    String AZURE_BLUET = "azure_bluet";
    String RED_TULIP = "red_tulip";
    String ORANGE_TULIP = "orange_tulip";
    String WHITE_TULIP = "white_tulip";
    String PINK_TULIP = "pink_tulip";
    String OXEYE_DAISY = "oxeye_daisy";
    String CORNFLOWER = "cornflower";
    String LILY_OF_THE_VALLEY = "lily_of_the_valley";
    String BRAIN_CORAL_FAN = "brain_coral_fan";
    String BUBBLE_CORAL_FAN = "bubble_coral_fan";
    String FIRE_CORAL_FAN = "fire_coral_fan";
    String HORN_CORAL_FAN = "horn_coral_fan";
    String DEAD_BRAIN_CORAL_FAN = "dead_brain_coral_fan";
    String DEAD_BUBBLE_CORAL_FAN = "dead_bubble_coral_fan";
    String DEAD_FIRE_CORAL_FAN = "dead_fire_coral_fan";
    String DEAD_HORN_CORAL_FAN = "dead_horn_coral_fan";
    String FERN = "fern";
    String BRAIN_CORAL_BLOCK = "brain_coral_block";
    String BUBBLE_CORAL_BLOCK = "bubble_coral_block";
    String FIRE_CORAL_BLOCK = "fire_coral_block";
    String HORN_CORAL_BLOCK = "horn_coral_block";
    String DEAD_TUBE_CORAL_BLOCK = "dead_tube_coral_block";
    String DEAD_BRAIN_CORAL_BLOCK = "dead_brain_coral_block";
    String DEAD_BUBBLE_CORAL_BLOCK = "dead_bubble_coral_block";
    String DEAD_FIRE_CORAL_BLOCK = "dead_fire_coral_block";
    String DEAD_HORN_CORAL_BLOCK = "dead_horn_coral_block";
    String INFESTED_COBBLESTONE = "infested_cobblestone";
    String INFESTED_STONE_BRICKS = "infested_stone_bricks";
    String INFESTED_MOSSY_STONE_BRICKS = "infested_mossy_stone_bricks";
    String INFESTED_CRACKED_STONE_BRICKS = "infested_cracked_stone_bricks";
    String INFESTED_CHISELED_STONE_BRICKS = "infested_chiseled_stone_bricks";
    String LILAC = "lilac";
    String TALL_GRASS = "tall_grass";
    String LARGE_FERN = "large_fern";
    String ROSE_BUSH = "rose_bush";
    String PEONY = "peony";
    String MOSSY_STONE_BRICKS = "mossy_stone_bricks";
    String CRACKED_STONE_BRICKS = "cracked_stone_bricks";
    String CHISELED_STONE_BRICKS = "chiseled_stone_bricks";

    String SANDSTONE_SLAB = "sandstone_slab";
    String COBBLESTONE_SLAB = "cobblestone_slab";
    String BRICK_SLAB = "brick_slab";
    String STONE_BRICK_SLAB = "stone_brick_slab";
    String QUARTZ_SLAB = "quartz_slab";
    String NETHER_BRICK_SLAB = "nether_brick_slab";
    String SANDSTONE_DOUBLE_SLAB = "sandstone_double_slab";
    String COBBLESTONE_DOUBLE_SLAB = "cobblestone_double_slab";
    String BRICK_DOUBLE_SLAB = "brick_double_slab";
    String STONE_BRICK_DOUBLE_SLAB = "stone_brick_double_slab";
    String QUARTZ_DOUBLE_SLAB = "quartz_double_slab";
    String NETHER_BRICK_DOUBLE_SLAB = "nether_brick_double_slab";
    String PURPUR_SLAB = "purpur_slab";
    String PRISMARINE_SLAB = "prismarine_slab";
    String DARK_PRISMARINE_SLAB = "dark_prismarine_slab";
    String PRISMARINE_BRICK_SLAB = "prismarine_brick_slab";
    String MOSSY_COBBLESTONE_SLAB = "mossy_cobblestone_slab";
    String SMOOTH_SANDSTONE_SLAB = "smooth_sandstone_slab";
    String RED_NETHER_BRICK_SLAB = "red_nether_brick_slab";
    String SMOOTH_RED_SANDSTONE_SLAB = "smooth_red_sandstone_slab";
    String POLISHED_ANDESITE_SLAB = "polished_andesite_slab";
    String ANDESITE_SLAB = "andesite_slab";
    String DIORITE_SLAB = "diorite_slab";
    String POLISHED_DIORITE_SLAB = "polished_diorite_slab";
    String GRANITE_SLAB = "granite_slab";
    String POLISHED_GRANITE_SLAB = "polished_granite_slab";
    String SMOOTH_QUARTZ_SLAB = "smooth_quartz_slab";
    String NORMAL_STONE_SLAB = "normal_stone_slab";
    String CUT_SANDSTONE_SLAB = "cut_sandstone_slab";
    String CUT_RED_SANDSTONE_SLAB = "cut_red_sandstone_slab";
    String PETRIFIED_OAK_SLAB = "petrified_oak_slab";
    String PETRIFIED_OAK_DOUBLE_SLAB = "petrified_oak_double_slab";
    String BRAIN_CORAL_WALL_FAN = "brain_coral_wall_fan";
    String DEAD_TUBE_CORAL_WALL_FAN = "dead_tube_coral_wall_fan";
    String DEAD_BRAIN_CORAL_WALL_FAN = "dead_brain_coral_wall_fan";
    String FIRE_CORAL_WALL_FAN = "fire_coral_wall_fan";
    String DEAD_BUBBLE_CORAL_WALL_FAN = "dead_bubble_coral_wall_fan";
    String DEAD_FIRE_CORAL_WALL_FAN = "dead_fire_coral_wall_fan";
    String DEAD_HORN_CORAL_WALL_FAN = "dead_horn_coral_wall_fan";
    String PURPUR_DOUBLE_SLAB = "purpur_double_slab";
    String PRISMARINE_DOUBLE_SLAB = "prismarine_double_slab";
    String DARK_PRISMARINE_DOUBLE_SLAB = "dark_prismarine_double_slab";
    String PRISMARINE_BRICK_DOUBLE_SLAB = "prismarine_brick_double_slab";
    String MOSSY_COBBLESTONE_DOUBLE_SLAB = "mossy_cobblestone_double_slab";
    String SMOOTH_SANDSTONE_DOUBLE_SLAB = "smooth_sandstone_double_slab";
    String RED_NETHER_BRICK_DOUBLE_SLAB = "red_nether_brick_double_slab";
    String SMOOTH_RED_SANDSTONE_DOUBLE_SLAB = "smooth_red_sandstone_double_slab";
    String POLISHED_ANDESITE_DOUBLE_SLAB = "polished_andesite_double_slab";
    String ANDESITE_DOUBLE_SLAB = "andesite_double_slab";
    String DIORITE_DOUBLE_SLAB = "diorite_double_slab";
    String POLISHED_DIORITE_DOUBLE_SLAB = "polished_diorite_double_slab";
    String GRANITE_DOUBLE_SLAB = "granite_double_slab";
    String POLISHED_GRANITE_DOUBLE_SLAB = "polished_granite_double_slab";
    String SMOOTH_QUARTZ_DOUBLE_SLAB = "smooth_quartz_double_slab";
    String NORMAL_STONE_DOUBLE_SLAB = "normal_stone_double_slab";
    String CUT_SANDSTONE_DOUBLE_SLAB = "cut_sandstone_double_slab";
    String CUT_RED_SANDSTONE_DOUBLE_SLAB = "cut_red_sandstone_double_slab";
    String LIGHT_BLOCK_1 = "light_block_1";
    String LIGHT_BLOCK_2 = "light_block_2";
    String LIGHT_BLOCK_3 = "light_block_3";
    String LIGHT_BLOCK_4 = "light_block_4";
    String LIGHT_BLOCK_5 = "light_block_5";
    String LIGHT_BLOCK_6 = "light_block_6";
    String LIGHT_BLOCK_7 = "light_block_7";
    String LIGHT_BLOCK_8 = "light_block_8";
    String LIGHT_BLOCK_9 = "light_block_9";
    String LIGHT_BLOCK_10 = "light_block_10";
    String LIGHT_BLOCK_11 = "light_block_11";
    String LIGHT_BLOCK_12 = "light_block_12";
    String LIGHT_BLOCK_13 = "light_block_13";
    String LIGHT_BLOCK_14 = "light_block_14";
    String LIGHT_BLOCK_15 = "light_block_15";
    String CHISELED_SANDSTONE = "chiseled_sandstone";
    String CUT_SANDSTONE = "cut_sandstone";
    String SMOOTH_SANDSTONE = "smooth_sandstone";
    String DARK_PRISMARINE = "dark_prismarine";
    String PRISMARINE_BRICKS = "prismarine_bricks";
    String RED_SAND = "red_sand";
    String DEPRECATED_PURPUR_BLOCK_1 = "deprecated_purpur_block_1";
    String PURPUR_PILLAR = "purpur_pillar";
    String DEPRECATED_PURPUR_BLOCK_2 = "deprecated_purpur_block_2";
    String CHISELED_QUARTZ_BLOCK = "chiseled_quartz_block";
    String QUARTZ_PILLAR = "quartz_pillar";
    String SMOOTH_QUARTZ = "smooth_quartz";
    String CHISELED_RED_SANDSTONE = "chiseled_red_sandstone";
    String CUT_RED_SANDSTONE = "cut_red_sandstone";
    String SMOOTH_RED_SANDSTONE = "smooth_red_sandstone";
    String CHIPPED_ANVIL = "chipped_anvil";
    String DAMAGED_ANVIL = "damaged_anvil";
    String DEPRECATED_ANVIL = "deprecated_anvil";
    String COARSE_DIRT = "coarse_dirt";
    String COLORED_TORCH_GREEN = "colored_torch_green";
    String COLORED_TORCH_PURPLE = "colored_torch_purple";

    String MOSSY_COBBLESTONE_WALL = "mossy_cobblestone_wall";
    String GRANITE_WALL = "granite_wall";
    String DIORITE_WALL = "diorite_wall";
    String ANDESITE_WALL = "andesite_wall";
    String SANDSTONE_WALL = "sandstone_wall";
    String BRICK_WALL = "brick_wall";
    String STONE_BRICK_WALL = "stone_brick_wall";
    String MOSSY_STONE_BRICK_WALL = "mossy_stone_brick_wall";
    String NETHER_BRICK_WALL = "nether_brick_wall";
    String END_STONE_BRICK_WALL = "end_stone_brick_wall";
    String PRISMARINE_WALL = "prismarine_wall";
    String RED_SANDSTONE_WALL = "red_sandstone_wall";
    String RED_NETHER_BRICK_WALL = "red_nether_brick_wall";
    String WET_SPONGE = "wet_sponge";
}
