package cn.nukkit.network.protocol.types;

@SuppressWarnings("all")
public interface UiContainerSlots {
    int CURSOR = 0;

    int ANVIL_INPUT_OFFSET = 1;
    int ANVIL_INPUT = ANVIL_INPUT_OFFSET + 0;
    int ANVIL_INGREDIENT = ANVIL_INPUT_OFFSET + 1;
    int ANVIL_INPUT_LAST = ANVIL_INGREDIENT;

    int STONECUTTER_INPUT_OFFSET = 3;
    int STONECUTTER_INPUT = STONECUTTER_INPUT_OFFSET + 0;
    int STONECUTTER_INPUT_LAST = STONECUTTER_INPUT;

    int TRADE2_INPUT_OFFSET = 4;
    int TRADE2_INPUT_A = TRADE2_INPUT_OFFSET + 0;
    int TRADE2_INPUT_B = TRADE2_INPUT_OFFSET + 1;
    int TRADE2_INPUT_LAST = TRADE2_INPUT_B;

    int TRADE_INPUT_OFFSET = 6;
    int TRADE_INPUT_A = TRADE_INPUT_OFFSET + 0;
    int TRADE_INPUT_B = TRADE_INPUT_OFFSET + 1;
    int TRADE_INPUT_LAST = TRADE_INPUT_B;

    int MATERIAL_REDUCER_INPUT_OFFSET = 8;
    int MATERIAL_REDUCER_INPUT = MATERIAL_REDUCER_INPUT_OFFSET + 0;
    int MATERIAL_REDUCER_INPUT_LAST = MATERIAL_REDUCER_INPUT;

    int LOOM_INPUT_OFFSET = 9;
    int LOOM_BANNER = LOOM_INPUT_OFFSET + 0;
    int LOOM_DYE = LOOM_INPUT_OFFSET + 1;
    int LOOM_PATTERN = LOOM_INPUT_OFFSET + 2;
    int LOOM_INPUT_LAST = LOOM_PATTERN;

    int CARTOGRAPHY_TABLE_INPUT_OFFSET = 12;
    int CARTOGRAPHY_TABLE_INPUT = CARTOGRAPHY_TABLE_INPUT_OFFSET + 0;
    int CARTOGRAPHY_TABLE_INGREDIENT = CARTOGRAPHY_TABLE_INPUT_OFFSET + 1;
    int CARTOGRAPHY_TABLE_INPUT_LAST = CARTOGRAPHY_TABLE_INGREDIENT;

    int ENCHANTING_TABLE_INPUT_OFFSET = 14;
    int ENCHANTING_TABLE_INPUT = ENCHANTING_TABLE_INPUT_OFFSET + 0;
    int ENCHANTING_TABLE_LAPIS_LAZULI = ENCHANTING_TABLE_INPUT_OFFSET + 1;
    int ENCHANTING_TABLE_INPUT_LAST = ENCHANTING_TABLE_LAPIS_LAZULI;

    int GRINDSTONE_INPUT_OFFSET = 16;
    int GRINDSTONE_INPUT = GRINDSTONE_INPUT_OFFSET + 0;
    int GRINDSTONE_INGREDIENT = GRINDSTONE_INPUT_OFFSET + 1;
    int GRINDSTONE_INPUT_LAST = GRINDSTONE_INGREDIENT;

    int COMPOUND_CREATOR_INPUT_OFFSET = 18;
    int COMPOUND_CREATOR_INPUT_0 = COMPOUND_CREATOR_INPUT_OFFSET + 0;
    int COMPOUND_CREATOR_INPUT_1 = COMPOUND_CREATOR_INPUT_OFFSET + 1;
    int COMPOUND_CREATOR_INPUT_2 = COMPOUND_CREATOR_INPUT_OFFSET + 2;
    int COMPOUND_CREATOR_INPUT_3 = COMPOUND_CREATOR_INPUT_OFFSET + 3;
    int COMPOUND_CREATOR_INPUT_4 = COMPOUND_CREATOR_INPUT_OFFSET + 4;
    int COMPOUND_CREATOR_INPUT_5 = COMPOUND_CREATOR_INPUT_OFFSET + 5;
    int COMPOUND_CREATOR_INPUT_6 = COMPOUND_CREATOR_INPUT_OFFSET + 6;
    int COMPOUND_CREATOR_INPUT_7 = COMPOUND_CREATOR_INPUT_OFFSET + 7;
    int COMPOUND_CREATOR_INPUT_8 = COMPOUND_CREATOR_INPUT_OFFSET + 8;
    int COMPOUND_CREATOR_INPUT_LAST = COMPOUND_CREATOR_INPUT_8;

    int BEACON_INPUT_OFFSET = 27;
    int BEACON_PAYMENT = BEACON_INPUT_OFFSET + 0;
    int BEACON_INPUT_LAST = BEACON_PAYMENT;

    int CRAFTING_INVENTORY_INPUT_OFFSET = 28;
    int CRAFTING_INVENTORY_INPUT_0 = CRAFTING_INVENTORY_INPUT_OFFSET + 0;
    int CRAFTING_INVENTORY_INPUT_1 = CRAFTING_INVENTORY_INPUT_OFFSET + 1;
    int CRAFTING_INVENTORY_INPUT_2 = CRAFTING_INVENTORY_INPUT_OFFSET + 2;
    int CRAFTING_INVENTORY_INPUT_3 = CRAFTING_INVENTORY_INPUT_OFFSET + 3;
    int CRAFTING_INVENTORY_INPUT_LAST = CRAFTING_INVENTORY_INPUT_3;

    int CRAFTING_TABLE_INPUT_OFFSET = 32;
    int CRAFTING_TABLE_INPUT_0 = CRAFTING_TABLE_INPUT_OFFSET + 0;
    int CRAFTING_TABLE_INPUT_1 = CRAFTING_TABLE_INPUT_OFFSET + 1;
    int CRAFTING_TABLE_INPUT_2 = CRAFTING_TABLE_INPUT_OFFSET + 2;
    int CRAFTING_TABLE_INPUT_3 = CRAFTING_TABLE_INPUT_OFFSET + 3;
    int CRAFTING_TABLE_INPUT_4 = CRAFTING_TABLE_INPUT_OFFSET + 4;
    int CRAFTING_TABLE_INPUT_5 = CRAFTING_TABLE_INPUT_OFFSET + 5;
    int CRAFTING_TABLE_INPUT_6 = CRAFTING_TABLE_INPUT_OFFSET + 6;
    int CRAFTING_TABLE_INPUT_7 = CRAFTING_TABLE_INPUT_OFFSET + 7;
    int CRAFTING_TABLE_INPUT_8 = CRAFTING_TABLE_INPUT_OFFSET + 8;
    int CRAFTING_TABLE_INPUT_LAST = CRAFTING_TABLE_INPUT_8;

    int MATERIAL_REDUCER_OUTPUT_OFFSET = 41;
    int MATERIAL_REDUCER_OUTPUT_0 = MATERIAL_REDUCER_OUTPUT_OFFSET + 0;
    int MATERIAL_REDUCER_OUTPUT_1 = MATERIAL_REDUCER_OUTPUT_OFFSET + 1;
    int MATERIAL_REDUCER_OUTPUT_2 = MATERIAL_REDUCER_OUTPUT_OFFSET + 2;
    int MATERIAL_REDUCER_OUTPUT_3 = MATERIAL_REDUCER_OUTPUT_OFFSET + 3;
    int MATERIAL_REDUCER_OUTPUT_4 = MATERIAL_REDUCER_OUTPUT_OFFSET + 4;
    int MATERIAL_REDUCER_OUTPUT_5 = MATERIAL_REDUCER_OUTPUT_OFFSET + 5;
    int MATERIAL_REDUCER_OUTPUT_6 = MATERIAL_REDUCER_OUTPUT_OFFSET + 6;
    int MATERIAL_REDUCER_OUTPUT_7 = MATERIAL_REDUCER_OUTPUT_OFFSET + 7;
    int MATERIAL_REDUCER_OUTPUT_8 = MATERIAL_REDUCER_OUTPUT_OFFSET + 8;
    int MATERIAL_REDUCER_OUTPUT_LAST = MATERIAL_REDUCER_OUTPUT_8;

    int CREATED_ITEM_OUTPUT = 50;

    int SMITHING_TABLE_INPUT_OFFSET = 51;
    int SMITHING_TABLE_INPUT = SMITHING_TABLE_INPUT_OFFSET + 0;
    int SMITHING_TABLE_INGREDIENT = SMITHING_TABLE_INPUT_OFFSET + 1;
    int SMITHING_TABLE_INPUT_LAST = SMITHING_TABLE_INGREDIENT;


    int LAST = SMITHING_TABLE_INPUT_LAST;
    int COUNT = LAST + 1;
}
