name: Publish package to GitHub Packages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: oracle
          cache: maven
      - name: Install dependencies
        run: |
          git clone --no-tags --depth 1 https://github.com/EaseCation/Network.git target/Network
          cd target/Network
          mvn -B clean install
      - name: Publish package
        run: mvn -B clean javadoc:jar deploy -P github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
