name: Java CI

on: [push, workflow_dispatch]

jobs:
  build:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          [
            21,
            25,
          ]
    steps:
      # Checkout side by side
      - name: Checkout Nukkit
        uses: actions/checkout@v5
        with:
          path: Nukkit
          submodules: true
      - name: Checkout Network repo
        uses: actions/checkout@v5
        with:
          repository: EaseCation/Network
          path: Network
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: oracle
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: false
          cache-overwrite-existing: true
          dependency-graph: generate-and-submit
      - name: Build with Gradle
        working-directory: Nukkit
        run: gradle shadowJar
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.welcome=never"
      - name: Archive artifacts
        uses: actions/upload-artifact@v5
        if: success()
        with:
          name: Nukkit-${{ matrix.java }}
          path: Nukkit/build/libs/nukkit-all.jar
