name: Java CI

on: [push, workflow_dispatch]

jobs:
  build:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          [
            21,
          ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: oracle
          cache: maven
      - name: Install dependencies
        run: |
          git clone --no-tags --depth 1 https://github.com/EaseCation/Network.git target/Network
          cd target/Network
          mvn -B clean install
      - name: Build with Maven
        run: mvn -B clean package
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: Nukkit-${{ matrix.java }}
          path: target/nukkit.jar
